Add C# 9 test cases - rules A* ... B*
SonarSource/sonar-dotnet pull request #3688
Opened 2020-10-28 17:21 UTC by andrei-epure-sonarsource

Related to #3668

2020-10-28 17:21 UTC, andrei-epure-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
> +        public static References MicrosoftVisualStudioQualityToolsUnitTestFramework => CreateWithCommandLine("VS.QualityTools.UnitTestFramework", "15.0.27323.2");
I had local failures... this is why I did this commit

2020-10-28 17:23 UTC, andrei-epure-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/AbstractTypesShouldNotHaveConstructorsTests.cs
> +                options: ParseOptionsHelper.FromCSharp9, checkMode: CompilationErrorBehavior.Ignore);
there's a compilation error - the compiler says it must be inside an executable project

2020-10-28 17:47 UTC, andrei-epure-sonarsource commented
I need to separate pre-C# 9 and C# 9 examples

2020-10-29 12:44 UTC, costin-zaharia-sonarsource requested changes

2020-10-29 12:44 UTC, costin-zaharia-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs
> +        async void MyMethod1(object o, EventArgs e)
Isn't `MyMethod1` almost the same with `MyMethod` and just parameter names changed? Can we remove it?

2020-10-29 12:44 UTC, costin-zaharia-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.cs
> +        private async void OnSuspending(object sender, ISuspendingEventArgs e)
pedantic: new line is missing

2020-10-29 13:21 UTC, andrei-epure-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/AesManagedShouldBeWithSecureModeTest.cs
> +            Verifier.VerifyAnalyzer(@"TestCases\AesManagedShouldBeWithSecureMode.TargetTyped.cs",
in general, it should be CSharp9, if it's only one added file
if there are multiple, then I differentiate by mentioning what's tested more specifically

I'll make the changes, for this one I should have used CSharp9

2020-10-29 14:48 UTC, costin-zaharia-sonarsource approved these changes
LGTM! Just 2 more minor comments left.

2020-10-29 14:48 UTC, costin-zaharia-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/AbstractTypesShouldNotHaveConstructors.Records.cs
> +﻿using System;
All using statements can be removed.

2020-10-29 15:42 UTC, merged