Add C# 9 tests for Implement* rules
SonarSource/sonar-dotnet pull request #3736
Opened 2020-11-10 16:40 UTC by pavel-mikula-sonarsource

Related to #3668
Reproduces #3734

2020-11-11 13:43 UTC, andrei-epure-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.CSharp9.cs
> +    public class SerializableClass : ISerializable
why do you need this?

2020-11-11 13:45 UTC, andrei-epure-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.CSharp9.cs
> +    public partial class Partial_SerializableDerived_CallingBase_GetObjectData_Class : SerializableClass
make this a record? same for `Partial_SerializableDerived_CallingBase_GetObjectData_Class` and `Partial_SerializableDerived_Not_CallingBase_GetObjectData_Class`?

2020-11-11 13:53 UTC, andrei-epure-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.CSharp9.cs
> +        { /*do something*/ }
I know it's a nitpick, but by removing the `/*do something*/` comment and by bringing the brackets on the same line with the method declaration, you'd remove some clutter from the test cases

```
public SerializableRecord() {}
protected SerializableRecord(SerializationInfo info, StreamingContext context) {}
public virtual void GetObjectData(SerializationInfo info, StreamingContext context) {}
```
is much better

2020-11-11 15:09 UTC, andrei-epure-sonarsource requested changes
left some comments

2020-11-11 15:09 UTC, andrei-epure-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementSerializationMethodsCorrectly.CSharp9.cs
> +        { }
you can now have `private partial void` and `private partial int` methods, would be nice to add a test

2020-11-12 11:32 UTC, pavel-mikula-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.CSharp9.cs
> +    public class SerializableClass : ISerializable
It's inherited below. Moved together.

2020-11-12 11:52 UTC, pavel-mikula-sonarsource commented on sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/ImplementISerializableCorrectly.CSharp9.cs
> +﻿using System;
Added reproducer for #1211

2020-11-12 17:33 UTC, andrei-epure-sonarsource approved these changes
LGTM

2020-11-12 17:33 UTC, merged