TestMethodShouldContainAssertion (S2699) NUnit return value
SonarSource/sonar-dotnet pull request #3799
Opened 2020-12-02 17:53 UTC by alexandersorokin

TestMethodShouldContainAssertion (S2699) rule takes into account a return value and the TestCaseSourceAttribute of NUnit test methods

Fixes #3751

2020-12-08 15:35 UTC, costin-zaharia-sonarsource commented
/azp run Sonar.Net.External

2020-12-08 16:01 UTC, costin-zaharia-sonarsource requested changes
Hi @alexandersorokin, this looks good. There are just two small comments related to codding style conventions.

2020-12-08 16:05 UTC, costin-zaharia-sonarsource commented
/azp run Sonar.Net

2020-12-08 20:34 UTC, alexandersorokin commented on analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
> +        private static readonly ImmutableArray<KnownType> NoExpectedResultTestMethodReturnTypes =
fixed

2020-12-08 20:34 UTC, alexandersorokin commented on analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
> +            IsTestCaseAttributeWithExpectedResult(a) ||
fixed

2020-12-09 08:18 UTC, costin-zaharia-sonarsource commented
/azp run Sonar.Net

2020-12-09 09:07 UTC, costin-zaharia-sonarsource approved these changes
LGTM! Thanks for the contribution!

2020-12-09 09:07 UTC, merged