Rule S2053: Hashes should include an unpredictable salt
SonarSource/sonar-dotnet pull request #3829
Opened 2020-12-10 14:40 UTC by costin-zaharia-sonarsource

Fixes #3722

2020-12-15 15:08 UTC, pavel-mikula-sonarsource requested changes
Mostly minor stuff and improvements

2020-12-16 09:49 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactoryTest.cs
> +                InitializationVectorShouldBeRandom,
It makes sense to clean up the code a bit like you mentioned and also to use directly the rule diagnostic ids. I will do this in a separate PR.

2020-12-16 10:01 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HashesShouldHaveUnpredictableSalt.cs
> +{
True, I also wanted to add this and I forgot 🤦

2020-12-16 10:04 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSalt.cs
> +                unchecked
Indeed, it is not needed since it should be `unchecked` by default.

2020-12-16 13:21 UTC, pavel-mikula-sonarsource commented on analyzers/rspec/cs/S2053_c#.html
> +<p>This rule raises an issue when a hashing function which has been specifically designed for hashing sensitive data, such as pbkdf2, is used with a
I saw you fixed the RSPEC in Jira. Will you update the description in this PR or do you intentionally postpone it to batch rspec update before release?

2020-12-16 13:23 UTC, costin-zaharia-sonarsource commented on analyzers/rspec/cs/S2053_c#.html
> +<p>This rule raises an issue when a hashing function which has been specifically designed for hashing sensitive data, such as pbkdf2, is used with a
I forgot to run the RSPEC. I will do the update in this PR.

2020-12-16 13:26 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HashesShouldHaveUnpredictableSalt.cs
> +{
Can you add more pressure to this case?
`salt = new byte[32];` - visit assignment path for to untracked symbol
`rng.GetBytes(shortSalt);` - visit sanitize path for untracked symbol

2020-12-16 13:27 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSalt.cs
> +            public string Message { get; }
Missed or intentionally omitted?

2020-12-16 13:34 UTC, pavel-mikula-sonarsource approved these changes
LGTM. Please check the remaining conversations before merging.

2020-12-16 13:35 UTC, pavel-mikula-sonarsource commented
There are 3 conversations to take a look at (2 hidden in the collapsed list)

2020-12-16 14:45 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSalt.cs
> +            public string Message { get; }
We usually let space between properties and I prefer to keep them as they are.

2020-12-16 14:52 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/HashesShouldHaveUnpredictableSalt.cs
> +{
Sure, I've added some. Just that after an assignment the symbol will get known state and we are be able to report on it.

2020-12-16 15:47 UTC, merged

2020-12-16 15:55 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/SymbolicExecutionAnalyzerFactoryTest.cs
> +                InitializationVectorShouldBeRandom,
Done in: #3846