Fix FP on S3626 (redundant jump) for "throw expressions"
SonarSource/sonar-dotnet pull request #3923
Opened 2021-01-07 19:51 UTC by lg2de

Fixes #3105

2021-01-08 07:19 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net.External

2021-01-08 09:15 UTC, pavel-mikula-sonarsource requested changes
Hi @lg2de, 

Thank you for taking time to look at this issue. I left one improvement comment, but it should be good to go otherwise.

2021-01-08 09:15 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantJumpStatement.cs
> +            return jumpBlock.JumpNode is ThrowStatementSyntax || ThrowExpressionSyntaxWrapper.IsInstance(jumpBlock.JumpNode);
More lightweight solution:
```suggestion
            return jumpBlock.JumpNode.IsAnyKind(SyntaxKind.ThrowStatement, SyntaxKindEx.ThrowExpression);
```

2021-01-08 09:49 UTC, lg2de commented
I've committed your suggestion, @pavel-mikula-sonarsource . I did not know this option. Hope the tests will succeed too.

2021-01-08 10:49 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2021-01-11 07:36 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2021-01-11 07:37 UTC, merged