GitHub workflow: Create PR
SonarSource/sonar-dotnet pull request #4093
Opened 2021-02-24 15:45 UTC by pavel-mikula-sonarsource

We should provide early visibility to PRs & draft PRs as they are a WIP and consume time.

If PR contains "Fixes #xxx", this action does nothing as there should already exist a card on Kanban with the original issue.

For standalone issues, it creates the card in "In progress" column and assigns PR to sender.

2021-02-26 13:59 UTC, andrei-epure-sonarsource commented on .github/workflows/CreatePullRequest.yml
> +            }
nitpick add line EOF

2021-02-26 14:01 UTC, andrei-epure-sonarsource requested changes

2021-02-26 14:01 UTC, andrei-epure-sonarsource commented on .github/workflows/CreatePullRequest.yml
> +            if(context.payload.pull_request.body.match(/Fixes\s*#\d+/gi)) {
could you please take into consideration all the accepted keywords? https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

even if our convention is "fixes", the github action should take all into account

2021-03-01 11:43 UTC, pavel-mikula-sonarsource commented on .github/workflows/CreatePullRequest.yml
> +                console.log("Skip, contains '" + matches[0] + "'");
Log output can be seen here https://github.com/pavel-mikula-sonarsource/GitHubActionPlayground/runs/2003487802?check_suite_focus=true

2021-03-01 11:54 UTC, andrei-epure-sonarsource approved these changes
LGTM :shipit:

2021-03-01 13:42 UTC, merged