Use FilesToAnalyze in S5753
SonarSource/sonar-dotnet pull request #4142
Opened 2021-03-10 15:51 UTC by csaba-sagi-sonarsource

Fixes #4111

2021-03-10 17:01 UTC, pavel-mikula-sonarsource requested changes
Some minor improvements

2021-03-11 11:20 UTC, pavel-mikula-sonarsource requested changes
Final line removal, I mean, polishing :D

2021-03-11 11:20 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DisablingRequestValidationTest.cs
> +                Path.Combine(root, SonarProjectConfig));
`WriteSonarProjectConfigToDisk(root);` does `Path.Combine(filesToAnalyzeDirectory, SonarProjectConfig)` inside and then is always followed by `Path.Combine(root, SonarProjectConfig)`. That's redundant.

Let's orchestrate the test like this and let the `Create` method return the full path.
```
DiagnosticVerifier.VerifyExternalFile(
                SolutionBuilder.Create().AddProject(AnalyzerLanguage.CSharp).GetCompilation(),
                new CS.DisablingRequestValidation(AnalyzerConfiguration.AlwaysEnabled),
                File.ReadAllText(Path.Combine(root, WebConfig)),
                CreateSonarProjectConfig(root));
```

2021-03-11 11:20 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/DisablingRequestValidationTest.cs
> +        private const string SonarProjectConfig = "SonarProjectConfig.xml";
This can be removed after addressing the other comment, as it will be needed only on a single place.

2021-03-11 11:20 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/DiagnosticVerifier.cs
> +            var analyzerOptions = string.IsNullOrWhiteSpace(sonarProjectConfigPath)? null : TestHelper.CreateOptions(sonarProjectConfigPath);
_Double nitpick:_ EOL before is not needed, previous block build opions. There's a space missing before `?` operator
```suggestion
            var analyzerOptions = string.IsNullOrWhiteSpace(sonarProjectConfigPath) ? null : TestHelper.CreateOptions(sonarProjectConfigPath);
```

2021-03-11 11:56 UTC, pavel-mikula-sonarsource approved these changes
LGTM!

2021-03-11 12:07 UTC, merged

2021-03-11 14:05 UTC, andrei-epure-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
> +                        && !b
I confirm it was intentional (I prefer explicit `==false` in a complex expression), but now when I look at it it's not that bad either.

2021-03-11 14:08 UTC, andrei-epure-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DisablingRequestValidationBase.cs
> +                        && !b
also, in the context of this rule, the "b" is actually the value that appears in tests (literal "false"), not a general boolean code condition.
So this makes the brain twist a little, too.