Fix S4143 FP with Indexers
SonarSource/sonar-dotnet pull request #4227
Opened 2021-04-12 15:20 UTC by csaba-sagi-sonarsource

Fixes #4178

2021-04-13 10:11 UTC, andrei-epure-sonarsource requested changes

2021-04-13 10:11 UTC, andrei-epure-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.cs
> +            public List<int> IntList { get; set; }
could you also add IntList2, and then the test above should be:

```
            first.IntList[0] = 1;
            first.IntList2[0] = 11;
            second.IntList[0] = 2;
            second.IntList2[0] = 22;
```
and no issue should be raised

Also, could you also add separate tests with various combinations of correctly raised issues like

```
            first.IntList[0] = 1;
            first.IntList2[0] = 2;
            first.IntList[0] = 3; // Noncompliant
            first.IntList2[1] = 4; // ok, different index
```

and 

```
            first.IntList[0] = 1;
            first.IntList2[1] = 2;
            first.IntList[1] = 3; 
            first.IntList2[1] = 4; // Noncompliant
```

and more compliant test cases like:
```
            first.IntList[0] = 1;
            first.IntList2[1] = 2;
            first.IntList[1] = 3; 
            first.IntList2[0] = 4;
```

2021-04-13 10:11 UTC, andrei-epure-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DoNotOverwriteCollectionElements.cs
> +            public List<int> IntList { get; set; }
also, can you add some tests with nested objects, like

```
private class ClassWithNested
{
            public ClassWithListProperty Alpha { get; set; }
            public ClassWithListProperty Beta { get; set; }
}
```

and something like

```
            first.Alpha.IntList[0] = 1;
            first.Alpha.IntList2[0] = 11;
            first.Beta.IntList[0] = 1111;
            first.Beta.IntList2[0] = 11111;
            second.Alpha.IntList[0] = 2;
             second.Alpha.IntList2[0] = 22;
            second.Beta.IntList[0] = 222;
            second.Beta.IntList2[0] = 2222;
```

and a noncompliant case with such nested structure

2021-04-13 15:50 UTC, andrei-epure-sonarsource approved these changes
LGTM

2021-04-13 17:09 UTC, merged

2021-04-14 11:14 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotOverwriteCollectionElements.cs
> +                    return ((MemberAccessExpressionSyntax)expression);
We don't need to change the type. And there's extra pair of parenthesis.
```
return expression;
```

2021-04-14 11:15 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/DoNotOverwriteCollectionElements.cs
> +                    //                 Name: b
This comment is not correct. We don't need `a`. We need `a.b` and that matches the implementation.