FP fix S1751 : triggered when returning a property inside try catch block
SonarSource/sonar-dotnet pull request #4300
Opened 2021-04-23 13:43 UTC by csaba-sagi-sonarsource

Fixes #2522

2021-04-26 07:34 UTC, pavel-mikula-sonarsource requested changes
Improvements suggested

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.vb
> +        ReadOnly Property FirstProperty As ReproducerClass
_Nitpick:_ There should be EOL around `Class` and `End Class`
```suggestion
    Public Class ReproducerClass
    
        ReadOnly Property FirstProperty As ReproducerClass
```

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.vb
> +    End Class
_Nitpick:_ NL before and after `End Class`
```suggestion
        End Function
        
    End Class
    
```

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/UnconditionalJumpStatementBase.cs
> +        protected abstract ILanguageFacade<TSyntaxKind> Language { get; }
This and the next abstract property `LoopStatements` should be together. And they won't need empty line between them.

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/UnconditionalJumpStatementBase.cs
> +                .TakeWhile(n => !rootExpression.Equals(n))
Line 108/109: Empty line in the middle of method signature makes it hard to read

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
> +                    && symbolInfo.Symbol is { } symbol
`SymbolInfo` is a struct so it cannot be `null`. You can go directly for it's symbol
```suggestion
                    && semanticModel.GetSymbolInfo(identifier).Symbol is { } symbol
```

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
> +                return returnStatementExpression is MemberAccessExpressionSyntax memberAccessExpression;
Unused variable
```suggestion
                return returnStatementExpression is MemberAccessExpressionSyntax;
```

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
> +                return returnStatementExpression is MemberAccessExpressionSyntax memberAccessExpression;
We should also check for `ElementAccessExpression` for `return arr[0]`

2021-04-26 07:34 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
> +                return returnStatementExpression is MemberAccessExpressionSyntax memberAccessExpression;
We should check `returnStatementExpression.DescendantNodesAndSelf().Any(x => x.IsAnyKind(...` to cover all nested cases. Like `(((arr[0])))` or other unexpected syntaxes like `return x = member.Item`

2021-04-26 12:03 UTC, csaba-sagi-sonarsource commented
WDYT about introducing ISyntaxHelper to the LanguageFacade to remove the duplication?

2021-04-26 14:49 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnconditionalJumpStatement.vb
> +    End Class
I wrote 
>and after `End Class`
🙂

2021-04-26 14:56 UTC, pavel-mikula-sonarsource requested changes
Last round

2021-04-26 14:56 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
> +                                                && semanticModel.GetSymbolInfo(identifier).Symbol is { } symbol
We don't need `IsKind` check before `is IdentifierNameSyntax` in this case. That can simplify the syntax like this:
```suggestion
                node.DescendantNodes().OfType<IdentifierNameSyntax>().Any(x => semanticModel.GetSymbolInfo(x).Symbol is { } symbol
```

2021-04-26 14:56 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnconditionalJumpStatement.cs
> +            protected override bool IsReturnStatement(SyntaxNode node) => node.IsKind(SyntaxKind.ReturnStatement);
Formatting (EOL between them, as they are not properties and they are not trivial)
```suggestion
            protected override bool IsAnyKind(SyntaxNode node, ISet<SyntaxKind> syntaxKinds) => 
                node.IsAnyKind(syntaxKinds);
            
            protected override bool IsReturnStatement(SyntaxNode node) => 
                node.IsKind(SyntaxKind.ReturnStatement);
```

2021-04-26 14:56 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/Rules/UnconditionalJumpStatement.cs
> +                node.DescendantNodes().Any(x => x.IsKind(SyntaxKind.IdentifierName)
Same as C# in this file

2021-04-27 09:34 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2021-04-27 09:34 UTC, merged