New rule: Use an Assert method to test if a specific exception was thrown
SonarSource/sonar-dotnet pull request #4628
Opened 2021-07-03 11:16 UTC by Corniel

As suggested on [the sonar forum](https://community.sonarsource.com/t/expectedexceptionattribute-is-an-anti-pattern/45415); an `Assert` method should be used to test if a specific exception was thrown, not an `[ExpectedException]` attribute.

-------------------------
# Description
Using `[ExpectedException]` is seen as bad practice for testing if a piece of code is throwing the expected exception,
as it can not distinguish if the exception was thrown by the code under test, or by any of the arranging code.

## Noncompliant Code Example
``` C#
[TestMethod]
[ExpectedException(typeof(ArgumentNullException))]
public void NullArgument_Throws()
{
    var arrange = new Instance(null);
	arrange.MethodUnderTest(null);
}
```

``` VB.NET
<TestMethod>
<ExpectedException(GetType(ArgumentNullException))>
Public Sub NullArgument_Throws()

    Dim arrange As New Instance(Nothing)
	arrange.MethodUnderTest(Nothing)

end Sub
```

## Compliant Solution
``` C#
[TestMethod]
public void NullArgument_Throws()
{
    var arrange = new Instance(null);
	Assert.ThrowsException<ArgumentNull>(() => arrange.MethodUnderTest(null));
}
```

``` VB.NET
<TestMethod>
Public Sub NullArgument_Throws()

    Dim arrange As New Instance(Nothing)
	Assert.ThrowsException(Of ArgumentNull)(Sub() arrange.MethodUnderTest(Nothing))

End Sub
```
**Labels**: bad-practice testability (not sure that is a existing label) 
**Message**: "Use an Assert method to test the thrown exception.
**Default Severity**: Major
**Impact**: Low
**Likelihood**: Medium
**Default Quality Profiles**: Sonar way (I would argue so)
**Covered Languages**: C#, VB.Net	
**Remediation Function**: ?
**Constant Cost**: 5min
**Analysis Level**: ?
**Syntactic Analysis Analysis Scope**: Test Sources

2021-07-09 15:20 UTC, csaba-sagi-sonarsource commented
@Corniel please take a look at rule [3431](https://rules.sonarsource.com/csharp/RSPEC-3431) as I think it is the same rule.

2021-07-10 10:31 UTC, Corniel commented
> 
> 
> @Corniel please take a look at rule [3431](https://rules.sonarsource.com/csharp/RSPEC-3431) as I think it is the same rule.

I guess so. Although this one also support VB.NET. I'll merge it with 3431 and extend it to VB.NET. May be, you could tell the person who asked for this feature on the Sonar forum, the rule already exists?!

2021-07-10 18:34 UTC, Corniel commented
Implementation added for VB.NET. I would like to challenge the choice of allowing the attribute for one line of code/expression-body. It might not fail in testing the exception, but having both mechanisms in a code base, is confusing.

2021-07-21 14:48 UTC, csaba-sagi-sonarsource commented
> Implementation added for VB.NET. I would like to challenge the choice of allowing the attribute for one line of code/expression-body. It might not fail in testing the exception, but having both mechanisms in a code base, is confusing.

There can be codebases where only the one liners are used, and It could be annoying for the users to be forced to change to `Assert.ThrowsException` for no obvious reason in their case.

2021-07-21 20:06 UTC, Corniel commented
> 
> 
> > Implementation added for VB.NET. I would like to challenge the choice of allowing the attribute for one line of code/expression-body. It might not fail in testing the exception, but having both mechanisms in a code base, is confusing.
> 
> There can be codebases where only the one liners are used, and It could be annoying for the users to be forced to change to `Assert.ThrowsException` for no obvious reason in their case.

To me, that feels far fetched, and up to that exceptional code base to disable it. But  if you want to support it, I'll add it.

2021-08-02 12:18 UTC, Corniel commented
Done.

2021-08-05 10:13 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/ExpectedExceptionShouldNotBeUsedAttributeBase.cs
> +        protected abstract bool HasMultiLineBody(SyntaxNode syntax);
NITPICK: According to our [coding style](https://github.com/SonarSource/sonar-dotnet/blob/master/docs/coding-style.md#class-members) abstract members should go third inside classes, so please move this abstract method below the Language property.

2021-08-05 10:18 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExpectedExceptionAttributeShouldNotBeUsedTest.cs
>  namespace SonarAnalyzer.UnitTest.Rules
NITPICK: According to our [coding style](https://github.com/SonarSource/sonar-dotnet/blob/master/docs/coding-style.md#naming-conventions) the test methods should have _CS and _VB suffixes and not prefixes. Please rename the test methods.

2021-08-05 10:20 UTC, csaba-sagi-sonarsource requested changes
Two coding style fixes are needed.

2021-08-05 10:29 UTC, csaba-sagi-sonarsource commented
/azp run Sonar.Net.External

2021-08-09 16:13 UTC, Corniel commented
@csaba-sagi-sonarsource Could you generate the proper resource file?

2021-08-13 15:15 UTC, csaba-sagi-sonarsource commented
> @csaba-sagi-sonarsource Could you generate the proper resource file?

@Corniel  I created the following [branch](https://github.com/SonarSource/sonar-dotnet/tree/%C4%8Daba/S3431-VBNET), feel free to cherry pick what you need.

2021-08-13 18:43 UTC, Corniel commented
> 
> 
> > @csaba-sagi-sonarsource Could you generate the proper resource file?
> 
> @Corniel I created the following [branch](https://github.com/SonarSource/sonar-dotnet/tree/%C4%8Daba/S3431-VBNET), feel free to cherry pick what you need.

Picked my cherries.

2021-08-16 09:07 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.Utilities/Rules.Description/S3431_cs.html
> +the <code>[ExpectedException]</code> attribute since an exception could be thrown from almost any line in the method.</p>
I just realised that I messed up with the RSPEC generation, please remove the square brackets around the ExpectedException in this line. Sorry for messing up.

2021-08-16 09:18 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2021-08-16 09:19 UTC, csaba-sagi-sonarsource commented
/azp run Sonar.Net

2021-08-16 12:35 UTC, Corniel commented
@csaba-sagi-sonarsource 
I was able to increase the coverage for C#. However, I could not make it work for the VB.NET equivalent.

``` VB.NET
  <Test>
    <ExpectedException(GetType(DivideByZeroException))>
    Public Function NoBody() ' Error ['BC30027] 'End Function' expected.
```
Both fails on complication, and does not increase coverage.

2021-08-16 12:36 UTC, Corniel reviewed
(I cannot cancel this?)

2021-08-16 12:37 UTC, csaba-sagi-sonarsource commented
Could you please also fix the code smell? (Remove the unnecessary using)

2021-08-16 13:04 UTC, csaba-sagi-sonarsource commented
/azp run Sonar.Net

2021-08-17 11:05 UTC, csaba-sagi-sonarsource commented
/azp run Sonar.Net

2021-08-17 13:07 UTC, merged