CSharpExecutableLinesMetric supports switch expressions, local functions and expression bodied methods
SonarSource/sonar-dotnet pull request #4695
Opened 2021-07-15 13:22 UTC by dmitry-golovinov-sonarsource

Fixes #4689

2021-07-15 13:39 UTC, dmitry-golovinov-sonarsource commented
PR got crazy rebased on Csaba's branch by my IDE. Please check only the last commit

2021-07-15 15:13 UTC, andrei-epure-sonarsource requested changes
some comments left.

Could you also do some tests with before and after and see how this changes the metrics, and document the findings on this PR? Because based on this PMs will have to communicate these changes to users that a change in coverage numbers will come (cc @tom-howlett-sonarsource - for SC and SQ users).

You can use one of the projects in  project being analyzed https://github.com/SonarSource/sonar-dotnet/tree/master/its/projects/ to start with, and add the new syntaxes (or write your own sample project).

Also, it would be nice to improve `AssertLinesOfCode` to parse comments and not have to pass the line  numbers, but to check those lines just like the UTs do with `// Noncompliant` - maybe open a `tooling` ticket for this?

2021-07-15 15:13 UTC, andrei-epure-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
> +                2, 7, 11);
please add +1 to line 2 for a visual helper

2021-07-15 15:13 UTC, andrei-epure-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
> +                              c is >= 'a' and <= 'z' or >= 'A' and <= 'Z'; // FN
remove `// FN`

2021-07-15 15:13 UTC, andrei-epure-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
> +              5, 6, 8, 15, 17);
please add `// +1` comments for visual aid

2021-07-15 15:23 UTC, andrei-epure-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpExecutableLinesMetric.cs
> +                    case SyntaxKindEx.SwitchExpressionArm:
please read this comment: https://github.com/SonarSource/sonar-dotnet/pull/4663/commits/a7d2a8624895d9acc539dc20948d5ec7bba2b5e3#r670270653

2021-07-15 15:26 UTC, andrei-epure-sonarsource commented
Please read the discussion on https://github.com/SonarSource/sonar-dotnet/pull/4663  - I am not sure we should do these updates before understanding better what we want to do.

2021-07-16 07:00 UTC, dmitry-golovinov-sonarsource commented
@andrei-epure-sonarsource I actually converted it to draft since I saw your comments after rebase and we had this discussion. I want either convert this to a background task and work on it when I have time or just pause it till the specification sprint (I am interested in it). WDYT?

2021-07-16 08:30 UTC, tom-howlett-sonarsource commented
Hi, thanks for flagging me here. I presume that this change will increase the executable lines and therefore has the potential to reduce coverage unexpectedly? It would be good to understand the magnitude of the impact on a test project as @andrei-epure-sonarsource has suggested. If I have that I can have a conversation with the SC/SQ PMs to talk about whether it's necessary to warn users and how.

2021-07-16 10:12 UTC, andrei-epure-sonarsource commented
@dmitry-golovinov-sonarsource I agree that we should first decide how to compute executable lines for switch expressions and also evaluate where we aren't consistent with existing specification, and then do one or a series of PRs to fix it. If you want as a background task you could do the evaluation of code coverage changes after this PR, it will help @tom-howlett-sonarsource understand the efforts needed for the sprint (e.g. do we need to update documentation etc).

2021-08-02 12:19 UTC, closed without merging