S3925: C#9 new partial method features support
SonarSource/sonar-dotnet pull request #4760
Opened 2021-08-04 11:26 UTC by csaba-sagi-sonarsource

Fixes #4411

2021-08-04 12:54 UTC, dmitry-golovinov-sonarsource reviewed
Overall looks good. Please reorganize the tests the way we've discussed

2021-08-04 12:54 UTC, dmitry-golovinov-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
> +                                                                       additionalLocations: implementationErrors.ToAdditionalLocations(),
Please align all the params on the new lines

2021-08-05 11:08 UTC, dmitry-golovinov-sonarsource approved these changes
LGTM! It's time to get a superhero to merge it :)

2021-08-05 11:08 UTC, dmitry-golovinov-sonarsource commented on analyzers/its/sources/Net5/Net5/S3925.Part1.cs
> +    public record SerializableRecord : ISerializable
Minor - normally we've agreed to put just 1 sample there, since all of them are already checked by UTs.

2021-08-05 12:38 UTC, andrei-epure-sonarsource requested changes

2021-08-05 12:38 UTC, andrei-epure-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
> +            return symbol.PartialImplementationPart != null
you are doing a null-check twice on `symbol.PartialImplementationPart`

2021-08-05 12:38 UTC, andrei-epure-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ImplementISerializableCorrectly.cs
> +            if (symbol == null)
this is called in three places:
- line 128 - `symbol` is null-checked in parent `if`
- line 154 - null-check is done at line 142
- line 181 - null-check done at line 174

So this cannot be `null` at this point, so you can remove it. It's a private method.

Eventually you can add a comment that it's expected to be null-checked in the caller.

2021-08-05 14:00 UTC, andrei-epure-sonarsource commented
there's a conflict to resolve

2021-08-05 15:01 UTC, merged