Fix S1172 FP: Parameter captured in a referenced generic local function
SonarSource/sonar-dotnet pull request #4770
Opened 2021-08-05 12:17 UTC by pavel-mikula-sonarsource

Fixes #4704

2021-08-10 11:10 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/CSharp/CSharpLiveVariableAnalysis.cs
> +            if (genericName.Parent.IsKind(SyntaxKind.InvocationExpression)
This is the same logic as in the `ProcessIdentifier(..)` above. We just don't need to care about the `if (IsLocalScoped(..` here.

2021-08-10 11:38 UTC, costin-zaharia-sonarsource requested changes
I think the solution looks good so far but the implementation is not yet complete.

Can you please add the following test case?
```
private static void M(this int someNumber, string someString)
{
    Action x = PrintSomeSum<int>;

    x();

    void PrintSomeSum<TOptions>() where TOptions : struct
    {
        Console.WriteLine(someNumber + someString.Length);
    }
}
```

2021-08-10 11:38 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/CSharp/CSharpLiveVariableAnalysis.cs
> +                && semanticModel.GetSymbolInfo(genericName).Symbol is IMethodSymbol method
Can be rewritten like: `&& semanticModel.GetSymbolInfo(genericName).Symbol is IMethodSymbol { MethodKind: MethodKindEx.LocalFunction } method`

2021-08-12 07:32 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2021-08-12 08:16 UTC, merged