Rule S1144: remove duplicate issues in top level statements
SonarSource/sonar-dotnet pull request #5081
Opened 2021-11-22 14:30 UTC by costin-zaharia-sonarsource

The symbols were processed twice, once for the Program symbol and the second time for the types defined in the top-level statement file.

2021-11-23 12:23 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
> +            && symbol.ContainingNamespace.IsGlobalNamespace;
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements#global-namespace

2021-11-23 12:48 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
> +            symbol.Name == "Program"
Maybe you can check additionally the `symbol.GetMembers()` collection for an `IMethodSymbol` with name `<Main>$`.

2021-11-23 12:51 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
> +            symbol.Name == "Program"
I think it would be useful to add this method in `SonarAnalyzer.Helpers.ISymbolExtensions` to reuse for other rules.

2021-11-23 12:52 UTC, mary-georgiou-sonarsource requested changes
LGTM, just a comment on `IsTopLevelProgram`

2021-11-24 09:08 UTC, mary-georgiou-sonarsource approved these changes
LGTM

2021-11-24 09:10 UTC, merged