RSPEC files for #4207
SonarSource/sonar-dotnet pull request #5171
Opened 2021-12-10 15:23 UTC by andrei-epure-sonarsource

cc @Corniel

2021-12-11 18:41 UTC, Corniel commented on analyzers/rspec/cs/S6354_c#.html
> +calls to static methods, and date/time functions are usually provided by system libraries as static methods.</p>
which behavior can not be changed/controlled

2021-12-11 18:43 UTC, Corniel requested changes
It has to be made explicit why statics functions might be an issue here.

2021-12-15 17:20 UTC, pavel-mikula-sonarsource commented
Is this PR needed? Changed files on a branch should do the trick.

2021-12-16 16:09 UTC, Corniel commented
> Is this PR needed? Changed files on a branch should do the trick.

It's both fine by me.

2021-12-24 11:39 UTC, andrei-epure-sonarsource commented
I've updated https://github.com/SonarSource/rspec/pull/285 and pushed the new version.
Indeed, this PR is not needed, the branch is fine.

2021-12-24 11:39 UTC, closed without merging

2021-12-24 11:40 UTC, andrei-epure-sonarsource commented
(don't delete the branch please)