Add concurrency options to VerifierBuilder
SonarSource/sonar-dotnet pull request #5214
Opened 2021-12-22 15:12 UTC by pavel-mikula-sonarsource

Contributes to #5186

Add more options:
* `.AddSnippet`
* `.AddTestReference`
* `.WithBasePath`
* `.WithConcurrentAnalysis`

This is a draft, rebase will be needed after #5231 is merged. The squash commits doesn't need a review for the same reason.

2021-12-23 11:12 UTC, costin-zaharia-sonarsource requested changes

2021-12-23 11:12 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
> +                .WithMessage("CSharp9: Unexpected build error [CS5001]: Program does not contain a static 'Main' method suitable for an entry point on line 1");
pedantic: the alignment is a bit off

2021-12-23 11:12 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
> +                .WithMessage("CSharp9: Unexpected build error [CS0825]: The contextual keyword 'var' may only appear within a local variable declaration or in script code on line 1");
pedantic: the alignment is a bit off

2021-12-23 11:12 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
> +                .Invoking(x => x.Verify()).Should().Throw<AssertFailedException>().WithMessage(
pedantic: the alignment is a bit off

2021-12-23 11:12 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
> +                .AddReferences(builder.References);
pedantic: the alignment is a bit off

2021-12-23 11:12 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
> +                project = project.AddSnippet(snippet);
Shouldn't we consider an API which can handle multiple snippets directly? We would be able to make at least this method a bit cleaner.

2022-01-11 12:37 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs
> +        /// <remarks>If we ever need to change the root outside TestCases directory, add WithRootPath(..)</remarks>
`WithRootPath` would change the curent `.\TestCases` root to whatever else (possibly absolute path outside the project) while `WithBasePath` would still append another part after the root.

2022-01-11 15:18 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs
> +        /// <remarks>If we ever need to change the root outside TestCases directory, add WithRootPath(..)</remarks>
Yes, please. It would be great to add an example since it could cause a lot of confusion.

2022-01-11 15:21 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/ProjectBuilder.cs
> +        }
```
        public ProjectBuilder AddSnippets(params string[] snippets) =>
            snippets.Aggregate(this, (current, snippet) => current.AddSnippet(snippet));
```

2022-01-11 15:25 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

Would be great to improve the comment for path methods and to use the more concise approach for adding the snippets.

2022-01-11 18:22 UTC, merged