Refactored SonarDiagnosticAnalyzer base classes
SonarSource/sonar-dotnet pull request #5283
Opened 2022-01-18 21:25 UTC by Corniel

Refactored all SonarDiagnosticAnalyzer base classes contained

``` C#
protected abstract ILanguageFacade<TSyntaxKind> Language { get; }
```

To inhertit from `SonarDiagnosticAnalyzer <TSyntaxKind>` instead (introduced in PR #5106 )

2022-01-19 09:18 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-01-19 09:37 UTC, pavel-mikula-sonarsource requested changes

2022-01-19 09:37 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/ClassNotInstantiatableBase.cs
> +        protected ClassNotInstantiatableBase() : base(DiagnosticId) { }
Both inheritors of theese class needs the `rule` -> `Rule` rename

2022-01-19 09:39 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/ClassNotInstantiatableBase.cs
> +        protected ClassNotInstantiatableBase() : base(DiagnosticId) { }
Fixed

2022-01-19 09:39 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-01-19 09:50 UTC, pavel-mikula-sonarsource commented
3 UTs throws `NullReferenceException`. Can you please take a look at that?

2022-01-19 15:24 UTC, Corniel commented
> 3 UTs throws `NullReferenceException`. Can you please take a look at that?

Done. Small issue, what should have been spotted If I would have run the tests locally, what I forgot (it was late, lame excuse).

2022-01-20 08:38 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-01-20 09:28 UTC, pavel-mikula-sonarsource approved these changes
LGTM, thank you @Corniel for taking the further step after introducing the generic base class.

2022-01-20 09:28 UTC, merged