Support branching in Symbolic Execution
SonarSource/sonar-dotnet pull request #5340
Opened 2022-01-28 15:03 UTC by pavel-mikula-sonarsource

Fixes #5306

2022-02-03 07:31 UTC, pavel-mikula-sonarsource commented
There's some CI issue, coverage was not computed.

2022-02-04 09:17 UTC, costin-zaharia-sonarsource requested changes

2022-02-04 15:15 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
> +                "AfterFinally");    // Dequeue after "if" branch
So is the `ToDo` there 😆

2022-02-04 15:53 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2022-02-07 12:51 UTC, pavel-mikula-sonarsource commented
There's a known issue with agents that prevents coverage from being processed. The PR was 100% covered in one of the successful runs.

2022-02-07 13:37 UTC, merged