Remove originalDeclaration from RoslynLVA
SonarSource/sonar-dotnet pull request #5490
Opened 2022-03-17 10:53 UTC by csaba-sagi-sonarsource

Contributes towards #5475

2022-03-17 11:04 UTC, pavel-mikula-sonarsource requested changes
See coments on #5475 from Round 2

2022-03-17 14:06 UTC, csaba-sagi-sonarsource commented
The coverage will improve once the LVA is plugged in to the Symbolic Execution engine. 
SymbolicExecutionRunnerTest will have test cases that will improve the coverage.
While the throw statement is there only to improve the message if we hit any new operations.

2022-03-18 08:16 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2022-03-18 08:20 UTC, pavel-mikula-sonarsource requested changes
I'd actually prefer to cover this properly. It should not be too complicated.

2022-03-18 12:18 UTC, pavel-mikula-sonarsource requested changes

2022-03-18 12:18 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
> +            new Context(cfg, lva).ValidateAllEmpty();
We don't need to repeat this, that's what the `Context` does for us:
```suggestion
new Context(code, AnalyzerLanguage.CSharp).ValidateAllEmpty;
```

2022-03-18 12:18 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
> +    public int Property => target = 42;
We'll need a small code fragment for each of the possible operations.

2022-03-18 15:30 UTC, pavel-mikula-sonarsource approved these changes
LGTM with some cleanup in UTs

2022-03-18 15:30 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
> +    private int target;
Here we don't need the assignment, right? So it can be just `property` and not `target`

2022-03-18 15:30 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
> +                var method = tree.GetRoot().DescendantNodes().First(x => x.RawKind == (int)syntaxKind);
It's not always a method.
```suggestion
                var node = tree.GetRoot().DescendantNodes().First(x => x.RawKind == (int)syntaxKind);
```

2022-03-18 15:30 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
> +    private int target;
Or just `Property => 42` and register for the literal

2022-03-18 16:16 UTC, merged