S4583: Add support for record structs
SonarSource/sonar-dotnet pull request #5569
Opened 2022-04-19 13:39 UTC by martin-strecker-sonarsource

2022-04-19 13:56 UTC, martin-strecker-sonarsource commented
I can't come up with test cases to show how the SyntaxKinds for record and record struct declarations make any difference. The reason is that the analyzer works like this:

1. Find a `BeginInvoke` invocation
1. Walk up the AST until any of the `ParentDeclarationKinds` is found. In most cases, this is any kind of method declaration, but can also be a class/record declaration (e.g. in cases like a field initializer: `public IAsyncResult result = caller.BeginInvoke(name: "Foo", 42, callback: null, @object: null);`)
1. From that point, a visitor is called, which visits every node below, except the visited node is of any of the `ParentDeclarationsKinds`! (This is a bit odd/unexpected behavior IMHO) (see https://github.com/SonarSource/sonar-dotnet/blob/c734b13f17351babe8de3f6b1a3fcfaa88981b9b/analyzers/src/SonarAnalyzer.Common/Rules/BeginInvokePairedWithEndInvokeBase.cs#L110-L112). These nodes are skipped.
1. So for classes/records basically only fields are visited and I can't come up with an `EndInvoke` call on a field initializer because `EndInvoke` returns `void`.

From my point of view, `ParentDeclarationKinds` of type `ClassDeclaration` and the like are just used to limit the scope of the Visitor (3), but the Visitor never finds an `EndInvoke` for any of the `ClassDeclaration`... node types.

2022-04-21 08:30 UTC, pavel-mikula-sonarsource commented
There's no reasonable scenario to make this work in a testable way => it doesn't make sense as the rule is currently implemented.

Let's 
* remove everything class-like from the `ParentDeclarationKinds` for C# and VB.NET (class, compilation unit, interface, records, struct) to keep the implementation clean and focused.
* remove the rule from the MMF
* rename this PR to a rule cleanup
* change `ParentMethodCContainsEndInvoke` like this, because it is wrong by-design (can have `null`, but cannot process it and ends in NRE)
```
        private bool ParentMethodContainsEndInvoke(SyntaxNode node, SemanticModel semantic) =>
            node.AncestorsAndSelf().FirstOrDefault(IsParentDeclaration) is { } parentContext
            && IsParentDeclarationWithEndInvoke(parentContext, semantic);
```

2022-04-21 08:30 UTC, pavel-mikula-sonarsource requested changes
Let's change the scope to cleanup

2022-04-25 11:47 UTC, martin-strecker-sonarsource commented
* [ ] remove everything class-like from the ParentDeclarationKinds for C# and VB.NET (class, compilation unit, interface, records, struct) to keep the implementation clean and focused.
* [ ] remove the rule from the MMF
* [ ] rename this PR to a rule cleanup
* [ ] change ParentMethodCContainsEndInvoke like this, because it is wrong by-design (can have null, but cannot process it and ends in NRE)

2022-04-25 11:52 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/BeginInvokePairedWithEndInvokeBase.cs
> -                && (node == Root || !rule.ParentDeclarationKinds.Contains(rule.Language.Syntax.Kind(node)));
Peach check should reveal any FP/FN that the removal of this line may cause.

2022-05-06 07:01 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2022-05-06 07:31 UTC, merged