Rule S6419: Azure Functions should be stateless
SonarSource/sonar-dotnet pull request #5651
Opened 2022-05-12 07:33 UTC by pavel-mikula-sonarsource

Fixes #5595

2022-05-17 06:40 UTC, martin-strecker-sonarsource requested changes
I have some general concerns about the implementation.
1. The analyzer is called on a lot of nodes (almost every line of code contains one or more of the listed node kinds)
1. Mutation outside the azure function or in local functions is likely missed.

I would propose to register for method declarations and start a class wide analysis from there. This is triggered in just a fraction of cases and can bail out easily for all non az function declarations. This would find all mutations taking place inside the containing class (e.g. By searching for write operations to mutable static fields). The downside is, that we end up reporting diagnostics multiple times if there is more than one azure function per class. We could overcome this limitation by registering for class declarations instead and searching for FunctionName decorated methods from there.

For instance azure functions it should work by checking for mutation of static fields (I think, Azure function instances are created per request, so instance fields should be fine to mutate, but I haven't checked the life cycle of these things yet).

Further: While most samples use static azure functions, I think that this is not the way these functions are used these days in the majority of production code. DI and the options system are omnipresent in any nontrivial az function. See e.g. this article for why that is the case (I would say Key Vault, httpclient and IOptions are all very good reasons to use the asp DI system in az functions).
https://dev.to/shibayan/a-new-era-of-azure-functions-development-6f2

2022-05-17 06:40 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CloudNative/AzureFunctionsStateless.cs
> +    public static void Assignment(object arg)
```suggestion
    public static void CompoundAssignment(object arg)
```

2022-05-17 06:40 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsStateless.cs
> +            if (context.IsAzureFunction()
Could go into before the switch in the merged RegisterSyntaxNodeActionInNonGenerated calls.

2022-05-17 06:40 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsStateless.cs
> +                && context.SemanticModel.GetSymbolInfo((target as ElementAccessExpressionSyntax)?.Expression ?? target).Symbol is { } symbol
I would prefer to move the `(target as ElementAccessExpressionSyntax)?.Expression ?? target` target part to the caller. The caller already extracts the right expression from the node and should do so entirely if possible.

2022-05-30 13:36 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsStateless.cs
> +                SyntaxKind.Argument);
This is easier to follow. And it's clearly visible what syntaxkind is related to what node type.

2022-05-30 13:40 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CloudNative/AzureFunctionsStateless.cs
> +        Property = 42;          // Noncompliant {{Do not modify a static state from Azure Function.}}
I don't see why that would be a good idea in Azure Funcion.

2022-05-30 13:44 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CloudNative/AzureFunctionsStateless.cs
> +    }
We prefer FNs over FPs, so I'll keep it as it is. Detecting azure-function-class would become too expensive with the current implementation

2022-05-30 14:54 UTC, martin-strecker-sonarsource approved these changes

2022-05-30 14:55 UTC, martin-strecker-sonarsource commented
LGTM

2022-06-01 07:20 UTC, merged