Fix FP S2325: Event Handlers should not be static
SonarSource/sonar-dotnet pull request #5706
Opened 2022-06-06 19:04 UTC by Corniel

Given the required scenario, I opted for a separate test case.

See: #5536

2022-06-08 14:52 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
> +    [DebuggerDisplay("{TypeName}")]
Not needed after rebase.

2022-06-08 14:53 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MemberShouldBeStatic.WinForms.cs
> +        private void SenderArgumentNotObject(string input, MyEventArgs e) { Handle(); }// Noncompliant
pedantic: insert a space between comment and method body

2022-06-08 15:06 UTC, costin-zaharia-sonarsource commented
/azp run Sonar.Net

2022-06-08 15:07 UTC, costin-zaharia-sonarsource requested changes
So far, it looks good to me. I've added a few minor comments and it needs a rebase.

2022-06-08 16:05 UTC, Corniel commented
Rebase done. And the two nitpicking issues.

2022-06-09 07:08 UTC, costin-zaharia-sonarsource commented
/azp run Sonar.Net

2022-06-09 14:48 UTC, Corniel commented
@costin-zaharia-sonarsource What do I have to change? As far as I'm concerned, the rebase have been applied.

2022-06-09 15:05 UTC, costin-zaharia-sonarsource commented
> @costin-zaharia-sonarsource What do I have to change? As far as I'm concerned, the rebase have been applied.

Nothing. I was waiting for the build to finish.

2022-06-09 15:05 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2022-06-09 15:05 UTC, merged