Implement S4060 - Avoid unsealed attributes - for VB.NET
SonarSource/sonar-dotnet pull request #5728
Opened 2022-06-12 16:57 UTC by Corniel

See #501

2022-07-28 07:19 UTC, pavel-mikula-sonarsource commented
@Corniel can you please rebase all your PRs on master? To remove the `RspecStrings.resx` files. It will help me to add the required resources around rspec.

2022-07-28 07:23 UTC, pavel-mikula-sonarsource commented
I've pushed a rspec scaffolding commit here. Please pull it before rebase 😃

2022-07-28 07:52 UTC, Corniel commented
Rebase done.

2022-07-28 07:56 UTC, Corniel commented on analyzers/rspec/vbnet/S4060_vb.net.html
> +Public NotInheritable Class MyAttribute    ' Noncompliant
' Noncompliant for the compliant part.

2022-07-28 08:11 UTC, pavel-mikula-sonarsource requested changes
Looks good, I left some minor polishing comments

2022-07-28 08:11 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/AvoidUnsealedAttributesBase.cs
> +            Language.SyntaxKind.ClassAndRecordDeclaration);
Record cannot inherit attribute and we should not register for it. You'll need to add `ClassDeclaration` to the facade
```suggestion
            Language.SyntaxKind.ClassDeclaration);
```
```suggestion
            Language.SyntaxKind.ClassDeclaration);
```

2022-07-28 08:11 UTC, pavel-mikula-sonarsource commented on analyzers/rspec/vbnet/S4060_vb.net.html
> +Public NotInheritable Class MyAttribute    ' Noncompliant
Fixed in rspec repo too

2022-07-28 08:11 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-07-28 08:47 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidUnsealedAttributes.vb
> +﻿Public Class PublicAttribute ' Noncompliant {{Seal this attribute or make it abstract.}}
There's a problem with the way how our test framework works. We can't assert locations `^^^^` on the first line.
Moving the problem to 2nd line will fix the issue.
```suggestion
' Test framework can't assert location on 1st line
﻿Public Class PublicAttribute ' Noncompliant {{Seal this attribute or make it abstract.}}
```

2022-07-28 09:27 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-07-28 11:12 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-07-28 11:14 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/AvoidUnsealedAttributesBase.cs
> +                    && symbol.DerivesFrom(KnownType.System_Attribute)
The coverage isn't great. Can you add this to cover the `DerivesFrom` scenario?
```
public class NotAnAttribute { }
```

2022-07-28 11:15 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/AvoidUnsealedAttributesBase.cs
> +                if (Language.Syntax.NodeIdentifier(c.Node) is { IsMissing: false } identifier
Also this to cover the `IsMissing`
```
public class { }    // Error CS1001  Identifier expected
```

2022-07-28 15:02 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-07-29 08:44 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2022-07-29 08:44 UTC, merged