Implement S1123 - Obsolete attributes need explanation - for VB.NET
SonarSource/sonar-dotnet pull request #5737
Opened 2022-06-14 06:45 UTC by Corniel

Fixes #6459

Rspec: https://github.com/SonarSource/rspec/pull/1428

2022-11-23 12:03 UTC, pavel-mikula-sonarsource commented
@Corniel Can you please rebase? I'll take this one next

2022-11-23 12:12 UTC, pavel-mikula-sonarsource requested changes
Nice one

2022-11-23 12:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.vb
> +Namespace S1123.ObsoleteAttributesNeedExplanation
Should not be needed (scaffolding noise, less is more)
```suggestion
```

2022-11-23 12:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.vb
> +﻿Imports System
Should not be needed in VB tests, it's in the global imports
```suggestion
```

2022-11-23 12:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.vb
> +'   ~~~~~~~~~~
`^` is the correct annotation
```suggestion
'   ^^^^^^^^^^
```

2022-11-23 20:11 UTC, Corniel commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.vb
> +        <Obsolete> ' Noncompliant
I've updated/extended the test scenarios. One note. By adding `' Noncompliant` to the VB.NET test cases, the claimed occurrence of the violation moved to the end of the line.

Also using `^2#8 `, and `@1` I was not able to get the precise matching right. I hope you can have a look.

2022-11-28 13:51 UTC, pavel-mikula-sonarsource requested changes
Few formatting nitpicks in the test file. I'll prepare the RSPEC part

2022-11-28 13:51 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/ObsoleteAttributesNeedExplanationTest.cs
> +    private readonly VerifierBuilder vbBuilder = new VerifierBuilder<VB.ObsoleteAttributesNeedExplanation>();
..as we use it in the rest (will require same changes below)
```suggestion
    private readonly VerifierBuilder builderCS = new VerifierBuilder<CS.ObsoleteAttributesNeedExplanation>();
    private readonly VerifierBuilder builderVB = new VerifierBuilder<VB.ObsoleteAttributesNeedExplanation>();
```

2022-11-28 13:51 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/ObsoleteAttributesNeedExplanationTest.cs
> +        .WithOptions(ParseOptionsHelper.FromCSharp9)
This is not needed, `WithTopLevelStatements()` will do that for us
```suggestion
```

2022-11-28 13:51 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/ObsoleteAttributesNeedExplanationTest.cs
> +        .WithTopLevelStatements()
I would revert this change to a single line. It fits into 200 chars so we're fine. It would need +4 indent anyway

2022-11-28 13:51 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/ObsoleteAttributesNeedExplanationTest.cs
> +        .Verify();
Let's revert this too

2022-11-28 14:07 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-11-29 08:05 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-11-29 13:31 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-11-29 14:33 UTC, pavel-mikula-sonarsource approved these changes
LGTM! Thank you for adding this rule

2022-11-29 14:33 UTC, merged