Implement S4225 - Extension method should not extend on object - for VB.NET
SonarSource/sonar-dotnet pull request #5749
Opened 2022-06-19 18:56 UTC by Corniel

Originally implemented via #763. [Documentation update](https://github.com/SonarSource/rspec/pull/1063) pending.

2022-06-22 23:39 UTC, Corniel commented
@pavel-mikula-sonarsource any ETA?

2022-06-23 06:13 UTC, pavel-mikula-sonarsource commented
My calendar is too busy last two weeks, it should be better next week.

2022-06-23 06:34 UTC, Corniel commented
> My calendar is too busy last two weeks, it should be better next week.

I tried hard to reduce the effort needed by others. :)

2022-07-01 12:15 UTC, pavel-mikula-sonarsource commented
Hi, I'm sorry, I won't be able to do this this week. And I'll be off the next one.

2022-07-11 15:01 UTC, pavel-mikula-sonarsource requested changes
Thank you @Corniel for taking a look into this. I left some minor comments

2022-07-11 15:01 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExtensionMethodShouldNotExtendObject.cs
> +    private bool IsExtension(AttributeSyntax attribute)
This is quite repetitive problem. On C# side, we have
https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.CSharp/Extensions/AttributeSyntaxExtensions.cs

We could copy/paste it to VB project as well for symetry.

2022-07-11 15:26 UTC, pavel-mikula-sonarsource commented
I've pushed the RSPEC change so you can try to run the UTs

2022-07-11 15:31 UTC, Corniel commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.vb
> +		<ExtensionAttribute>
No, that will not compile. I tried it. ;)

2022-07-12 06:04 UTC, Corniel commented
Applied all.

2022-07-12 07:09 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.vb
> +		<ExtensionAttribute>
I just tried this and it compiled in empty solution:
```
    <System.Runtime.CompilerServices.ExtensionAttribute>
    Public Sub FullName(Arg As Object)
    End Sub

    <Runtime.CompilerServices.ExtensionAttribute>
    Public Sub ImplicitSystem(Arg As Object)
    End Sub

    <System.Runtime.CompilerServices.Extension>
    Public Sub ImplicitAttribute(Arg As Object)
    End Sub

    <Runtime.CompilerServices.Extension>
    Public Sub ImplicitSystemAndAttribute(Arg As Object)
    End Sub
```
Wasn't there some copy/paste issue?

2022-07-12 07:14 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.vb
> +Namespace S4225.ExtensionMethodShouldNotExtendObject
Historically, namespaces were part of the template that scaffolded a new rule. That's how it polluted the existing files. For most of the rules, it's useless noise that is not relevant for the purpose of the rule.

They make sense when the `namespace` or `using` matters. Or when the test case file is really big and we need to split it into topics and class names are not enough there.

In this rule, the test case was pretty weak and you've rewritten the whole thing. So it makes sense to clean the namespace too. I wouldn't do it on a bigger file.

2022-07-12 07:20 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
> +            expression is AttributeSyntax x
This was not addressed

2022-07-12 07:22 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExtensionMethodShouldNotExtendObject.cs
> +    private bool IsExtension(AttributeSyntax attribute)
What I meant was to have `AttributeSyntaxExtensions.IsKnownType` on VB side, just as we have it on C#. And use that. The `IsExtension` is too specific to be an extension by itself.

2022-07-12 07:24 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExtensionMethodShouldNotExtendObject.cs
> +            .Any(x => x.IsExtension());
This is now clean and easy to follow, I'd make it a single line.
```suggestion
        && declaration.AttributeLists.SelectMany(x => x.Attributes).Any(x => x.IsExtension());
```

2022-07-12 07:29 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/Rules/ExtensionMethodShouldNotExtendObject.cs
> +            .SelectMany(x => x.Attributes)
Seing this, let's add test cases with multiple attributes and multi-attribute syntaxes:
```
    <Extension, DebuggerStepThrough()>
    Public Sub MoreAttributes1(Arg As Object)
    End Sub

    <Extension>
    <DebuggerStepThrough()>
    Public Sub MoreAttributes2(Arg As Object)
    End Sub
```

2022-07-12 08:04 UTC, Corniel commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.vb
> +Namespace S4225.ExtensionMethodShouldNotExtendObject
@pavel-mikula-sonarsource I agree. But I try to follow most of your conventions. I'm happy to drop noisy namespaces.

2022-07-12 08:09 UTC, Corniel commented on analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
> +            expression is AttributeSyntax x
I do not need it any more. Note that `AttributeSytnax` lacks an `Identifer` node.

2022-07-13 06:40 UTC, pavel-mikula-sonarsource commented
I've resolved some conversations, there are few UTs to be added.

2022-07-13 06:40 UTC, pavel-mikula-sonarsource commented
I've resolved some conversations, there are few UTs to be added.

2022-07-13 09:59 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.vb
> +		<ExtensionAttribute>
I've also added these cases so we can move forward with this PR

2022-07-13 09:59 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-07-13 10:38 UTC, Corniel commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExtensionMethodShouldNotExtendObject.vb
> +    Public Sub ImplicitAttribute(Arg As Object) ' Noncompliant
Descriptive names! Good. That is not always the case in some older test case files.

2022-07-13 11:00 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-07-15 15:13 UTC, pavel-mikula-sonarsource commented
@Corniel can you please rebase? We've (finally) deleted `RspecStrings.resx` file so we need to remove it from this PR too.

2022-07-15 20:22 UTC, Corniel commented
Rebase done.

2022-07-18 14:45 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-07-25 11:41 UTC, merged