Support try/finally nested in try/catch in SE
SonarSource/sonar-dotnet pull request #5795
Opened 2022-06-29 12:20 UTC by pavel-mikula-sonarsource

Related to #5710

2022-06-30 08:34 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.TryCatch.cs
> +                Monitor.Enter(obj);     // Noncompliant FP
Adding repro for the next PR

2022-06-30 08:54 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2022-06-30 08:55 UTC, costin-zaharia-sonarsource approved these changes

2022-06-30 08:55 UTC, costin-zaharia-sonarsource requested changes
Waiting for tests to pass first.

2022-07-01 08:16 UTC, costin-zaharia-sonarsource approved these changes

2022-07-01 08:16 UTC, merged