Implement S3871- Exceptions should be public - for VB.NET
SonarSource/sonar-dotnet pull request #5822
Opened 2022-07-09 14:58 UTC by Corniel

Moved logic to a base class, and added VB.NET tests.

2022-11-02 09:08 UTC, pavel-mikula-sonarsource commented
@Corniel can you rebase please?

2022-11-02 14:02 UTC, Corniel commented
Rebase done.

2022-11-03 09:10 UTC, pavel-mikula-sonarsource requested changes
Looks quite good, will you create the rspec PR too?

2022-11-03 10:54 UTC, Corniel commented on analyzers/src/SonarAnalyzer.Common/Rules/ExceptionsShouldBePublicBase.cs
> +                && classSymbol.BaseType.IsAny(BaseTypes))
@pavel-mikula-sonarsource I'm not sure. I didn't want to change the behavior (yet). There are testcases that allow to have non-public exceptions on exceptions derived from others.

My main goal was to get this one working for both lanuages first.

2022-11-03 19:06 UTC, Corniel commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/ExceptionsShouldBePublicTest.cs
> +        .WithConcurrentAnalysis(false)
I can not recall clearly; I thought it had something to do with adding the extra namespace scope.. It's some months ago.  ;)

However, It now works like a charm, so I removed the line.

2022-11-03 19:12 UTC, Corniel commented on analyzers/src/SonarAnalyzer.Common/Rules/ExceptionsShouldBePublicBase.cs
> +                    c.ReportIssue(Diagnostic.Create(Rule, Language.Syntax.NodeIdentifier(c.Node).Value.GetLocation()));
Your example will never return an `INamedTypeSymbol`, so that is not needed. I added the scenario however.

2022-11-03 19:22 UTC, Corniel commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionsShouldBePublic.cs
> +internal class InternalException : Exception
About the exceptions that are taken into account. The [RSPEC](https://rules.sonarsource.com/csharp/RSPEC-3871) explicitly mentions it:
> This rule ignores Exception types that are not derived directly from `System.Exception`, `System.SystemException`, or `System.ApplicationException`.

It is not explained **why**, but by changing the behavior, this part of the documentation has to be adjusted too.

I'm not sure how many new issues there will be reported amongst customers, and if that is desirable or not, that your call.

2022-11-04 12:24 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionsShouldBePublic.cs
> +internal class InternalException : Exception
Ok, let's just keep the UT as is and remove the "FN" comment

2022-11-04 12:24 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExceptionsShouldBePublic.cs
> +internal class LastException : MiddleException { } // FN
```suggestion
internal class LastException : MiddleException { }
```

2022-11-04 12:25 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Rules/ExceptionsShouldBePublicBase.cs
> +                    c.ReportIssue(Diagnostic.Create(Rule, Language.Syntax.NodeIdentifier(c.Node).Value.GetLocation()));
Indeed, we're fine with `.Value.` then

2022-11-04 12:26 UTC, pavel-mikula-sonarsource reviewed
Looks good so far, I need to update RSPEC repository and push the rspec scaffolding before running UTs

2022-11-04 12:57 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-11-04 13:14 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2022-11-04 13:34 UTC, Corniel commented on analyzers/rspec/vbnet/S3871_vb.net.html
> +<p>The point of having custom exception types is to convey more information than is available in standard types. But custom exception types must be
I would ague that this should be in the generic part, and that only the compliant and non-compliant should be language specific?

2022-11-04 13:34 UTC, Corniel reviewed
LGTM!

2022-11-04 16:07 UTC, pavel-mikula-sonarsource commented
Waiting for RSPEC PR to be reviewed and merged: https://github.com/SonarSource/rspec/pull/1375

2022-11-07 09:34 UTC, pavel-mikula-sonarsource commented
/azp run Sonar.Net

2022-11-09 07:32 UTC, merged