Set NotNull constraints for member references in SE
SonarSource/sonar-dotnet pull request #5882
Opened 2022-07-20 13:27 UTC by pavel-mikula-sonarsource

Contributes to https://github.com/SonarSource/sonar-dotnet/issues/5860

2022-07-20 18:15 UTC, martin-strecker-sonarsource requested changes
Some test are missing IMHO.

2022-07-20 18:15 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        }
We have get and set operations. Would be nice to have a data test for all the other operators
* Invocation
* Event subscription
* Post and Pre operators (++)
* Casts

2022-07-20 18:15 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        }
A test for dynmic binding is missing
```cs
, dynamic arg
arg.BlaBla();
arg[0] = 0;
arg.Prop = 42;
// ...
```

2022-07-22 14:20 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +Tag(""AfterIndexer"", indexer);
I don't get this. The functionality of how symbols are tracked is a responsibility of another UT that we don't need to re-do here.

2022-07-22 14:22 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        }
We are not field-sensitive, we have no symbolic value for `arg.Joe` so we can't build constraints for that (and anything inside that).

2022-07-22 14:24 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        }
Invocation is another PR.
I'll check how event subscription can be done.
I don't see a reason to build constraints on `++`, operators does not guarantee `NotNull`
Cast doesn't guarantee `NotNull` either.

2022-07-22 14:43 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        }
I'll do the dynamic stuff later, if I have some time. That one is not that much valuable.

2022-07-25 09:19 UTC, martin-strecker-sonarsource approved these changes
Can we overcome the nesting limitation?

2022-07-25 09:19 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        }
> We are not field-sensitive, we have no symbolic value for arg.Joe so we can't build constraints for that (and anything inside that).

That is unfortunate and very limiting. Are there plans to overcome this?

2022-07-25 09:46 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        }
It's an idea for `the next big thing`, nothing is specified.

2022-07-25 09:46 UTC, merged