SE: Learn ObjectConstraint on branching from constant pattern
SonarSource/sonar-dotnet pull request #6037
Opened 2022-08-25 16:02 UTC by pavel-mikula-sonarsource

Contributes to #5970

Rebase will be needed, commit `Squash Equals` doesn't need a review.

2022-08-26 09:41 UTC, martin-strecker-sonarsource requested changes
The comment should be updated.

2022-08-26 11:07 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Pattern.cs
> +                if (value.Constraint<BoolConstraint>() is { } boolConstraint && !useOpposite)   // Cannot use opposite on booleans. If it is not "true", it could be null, false or any other type
`is true` and `is false` is not practically needed for boolean types. The comment explains what happens with the rest.

2022-08-26 11:07 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
> +                .And.ContainSingle(x => x.HasConstraint(ObjectConstraint.NotNull));
We'll hopefully improve the assertion framework

2022-08-26 11:08 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
> +Tag(""End"", arg);";
While it branches, it makes the branching flow less obvious with the return value

2022-08-29 07:13 UTC, martin-strecker-sonarsource approved these changes
LGTM

2022-08-29 09:37 UTC, merged