SE: Refactor ProcessOperation to OperationDispatcher
SonarSource/sonar-dotnet pull request #6127
Opened 2022-09-22 11:03 UTC by pavel-mikula-sonarsource

2022-09-22 15:17 UTC, martin-strecker-sonarsource requested changes
I would declare `Convert` as `protected abstract T Convert(IOperation operation);` to be more object-oriented. Otherwise, this is much better than before.

2022-09-22 15:17 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ReDimClause.cs
> +    protected override System.Func<IOperation, IReDimClauseOperationWrapper> Convert => IReDimClauseOperationWrapper.FromOperation;
```suggestion
    protected override Func<IOperation, IReDimClauseOperationWrapper> Convert => IReDimClauseOperationWrapper.FromOperation;
```

2022-09-22 15:17 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
> +    protected override System.Func<IOperation, ILocalReferenceOperationWrapper> Convert => ILocalReferenceOperationWrapper.FromOperation;
```suggestion
    protected override Func<IOperation, ILocalReferenceOperationWrapper> Convert => ILocalReferenceOperationWrapper.FromOperation;
```

2022-09-22 15:17 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
> +    protected override System.Func<IOperation, IParameterReferenceOperationWrapper> Convert => IParameterReferenceOperationWrapper.FromOperation;
```suggestion
    protected override Func<IOperation, IParameterReferenceOperationWrapper> Convert => IParameterReferenceOperationWrapper.FromOperation;
```

2022-09-22 15:17 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
> +    protected override System.Func<IOperation, IFieldReferenceOperationWrapper> Convert => IFieldReferenceOperationWrapper.FromOperation;
```suggestion
    protected override Func<IOperation, IFieldReferenceOperationWrapper> Convert => IFieldReferenceOperationWrapper.FromOperation;
```

2022-09-22 15:17 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
> +    protected override System.Func<IOperation, IPropertyReferenceOperationWrapper> Convert => IPropertyReferenceOperationWrapper.FromOperation;
```suggestion
    protected override Func<IOperation, IPropertyReferenceOperationWrapper> Convert => IPropertyReferenceOperationWrapper.FromOperation;
```

2022-09-22 15:17 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
> +    protected override System.Func<IOperation, IArgumentOperationWrapper> Convert => IArgumentOperationWrapper.FromOperation;
```suggestion
    protected override Func<IOperation, IArgumentOperationWrapper> Convert => IArgumentOperationWrapper.FromOperation;
```

2022-09-22 15:24 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
> +    protected override System.Func<IOperation, IArgumentOperationWrapper> Convert => IArgumentOperationWrapper.FromOperation;
This will disappear after the other OOP suggestions - same for all friends below

2022-09-22 15:26 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Processor.cs
> +    protected abstract Func<IOperation, T> Convert { get; }
I disagree with the "bit more verbose". It's actually shorter :)

2022-09-23 09:01 UTC, martin-strecker-sonarsource approved these changes
LGTM. One suggestion left.

2022-09-23 09:01 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Processor.cs
> +    protected abstract T Convert(IOperation operation);
Consider naming the method `FromOperation`.

2022-09-23 09:57 UTC, merged