Support new C#11 string types in CopyPasteTokenAnalyzer and TokenTypeAnalyzer
SonarSource/sonar-dotnet pull request #6204
Opened 2022-10-12 13:45 UTC by csaba-sagi-sonarsource

2022-10-13 13:29 UTC, costin-zaharia-sonarsource requested changes

2022-10-13 13:29 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/CopyPasteTokenAnalyzer/Unique.CSharp11.cs
> +        var interpolatedWithWhitespaceToken = $"This literal should be $str but the whitespace between interpolation will not: {x} {x}";
As far as I can tell this message is misleading, the space is actually a string. See:
![image](https://user-images.githubusercontent.com/56015273/195609803-b8936da7-5180-4b06-a3b2-6e392274dc66.png)

2022-10-13 16:16 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/CopyPasteTokenAnalyzer.cs
> +                                     SyntaxKind.InterpolatedStringTextToken,
No, we only want to replace the "body" of the string with the $str. and not also the being and and tokens.

2022-10-14 08:33 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2022-10-14 08:33 UTC, merged