C#11 - Add TC for Raw string literal
SonarSource/sonar-dotnet pull request #6208
Opened 2022-10-13 11:40 UTC by cristian-ambrosini-sonarsource

2022-10-13 15:59 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/ControlCharacterInStringTest.cs
>          public void ControlCharacterInString() =>
NITPICK: rename the test to ControlCharacterInString_CSharp8. As it is applicable only from chsarp8.

2022-10-13 16:02 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/DeadStoresTest.cs
> +            sonarCfg.AddPaths("DeadStores.SonarCfg.cs")
NITPICK:  the .Verify() invocation should go to the same line. Simple test case where it  contains only addpaths and verify we tend to put on the same line.
I am not sure it is documented anywhere (If it is not in the coding style than we should most probably document it)

2022-10-13 16:03 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/DeadStoresTest.cs
> +            sonarCfg.AddPaths("DeadStores.SonarCfg.cs")
Applies for the whole PR.

2022-10-13 16:08 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/InsecureEncryptionAlgorithmTest.cs
> +using SonarAnalyzer.Common;
Unnecessary usings, please remove.

2022-10-13 16:09 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/InsecureEncryptionAlgorithmTest.cs
>          [TestMethod]
NITPICK:
According to our coding style: Each compiler directive outside method body (namely #if/#endif) should be preceded and followed by an empty line.
Which means you need an empty line both there and and the endif.

2022-10-13 16:11 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/UriShouldNotBeHardcodedTest.cs
> +        [TestMethod]
NITPICK: An empty line missing here.

2022-10-13 16:12 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/UriShouldNotBeHardcodedTest.cs
> +#endif
NITPICK: And also here.

2022-10-14 08:24 UTC, andrei-epure-sonarsource commented
(saw this when doing backlog cleanup - please don't use acronyms like TC - we don't know what this is and the PR title will show up in the history; use words instead of acronyms)

2022-10-14 14:16 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SqlKeywordsDelimitedBySpaceTest.cs
>          public void SqlKeywordsDelimitedBySpace() =>
Needs renaming to SqlKeywordsDelimitedBySpace_Csharp8

2022-10-14 14:16 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.CSharp11.cs
> +    context.Query<User>().FromSql(constQuery, parameters); // Compliant
Please add a noncompliant case too, one where the strings are not constant.

2022-10-14 14:29 UTC, csaba-sagi-sonarsource requested changes
One last round of changes.

2022-10-14 16:26 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-10-14 16:26 UTC, merged