Greg/nameof tests
SonarSource/sonar-dotnet pull request #6234
Opened 2022-10-20 07:41 UTC by gregory-paidis-sonarsource

2022-10-26 15:23 UTC, costin-zaharia-sonarsource commented
We might want to add a test case for `AvoidExcessiveClassCoupling` as well. It seems that we look for `nameof` only in invocations.

Attributes have an argument list but they are not considered invocations: 
![image](https://user-images.githubusercontent.com/56015273/198067706-a1c147b0-d9e5-4945-aa0b-72feca017d2f.png)

2022-10-26 19:26 UTC, costin-zaharia-sonarsource requested changes
I would add a test case also for:
- `ControllingPermissions.cs`
```
[Obsolete(nameof(httpContext.User))] // Noncompliant, FN
void HttpContextUser(HttpContext httpContext)
{
}
```
This happens because the `PropertyAccessTracker` subscribes to `SimpleMemberAccessExpression`.
- there are other trackers as well that use this kind of subscription. Could you please check them and the rule that are using them too? (as far as I can tell the rules that use the `MatchSetter` are not a problem and also the ones that look for symbols as the symbol will be null)

2022-10-28 08:56 UTC, gregory-paidis-sonarsource commented
> We might want to add a test case for AvoidExcessiveClassCoupling as well. It seems that we look for nameof only in invocations. 

I do not believe this is necessary. Since `AvoidExcessiveClassCoupling` checks for method arguments, a potential type dependency would have already been counted from the `ParameterSyntax` node on the method declaration, which is what the nameof would reference.

2022-10-31 10:09 UTC, gregory-paidis-sonarsource commented
> I would add a test case also for:
> 
> * `ControllingPermissions.cs`

After looking into this, it seems like we do not raise for the `HttpContext.User`, but the reason for not raising is not the usage of the nameof as it should work, but because of how the type gets resolved. 

For HttpContext, we resolve it to this known type:

`System_Web_HttpContext = new("System.Web.HttpContext");`

This is the where the type resides in [.net framework](https://learn.microsoft.com/en-us/dotnet/api/system.web.httpcontext?view=netframework-4.8), but not where it resides in [.net core](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext?view=aspnetcore-7.0)

They seem to have moved it from `System.Web` to `Microsoft.AspNetCore.Http`, meaning that even if you normally access `httpContext.User` it fails to raise the issue:

```csharp
var user = httpContext.User; // Compliant, False Negative (C#11)
```

If you add the following to the PropertyTracker, it marks both the `httpContext.User` and the `nameof(httpContext.User)` as Noncompliant:

```csharp
Microsoft_AspNetCore_Http_HttpContext = new("Microsoft.AspNetCore.Http.HttpContext");
```

2022-10-31 12:53 UTC, costin-zaharia-sonarsource requested changes

2022-10-31 12:53 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ControllingPermissions.CSharp11.cs
> +void HttpContextUser(HttpContext httpContext)
The table is not populated for this rule. You need to specify also "Implement" to fix the FNs and the FP below.

2022-10-31 12:53 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
> +          .WithConcurrentAnalysis(false);
```suggestion
        private readonly VerifierBuilder builder = new VerifierBuilder<SymbolicExecutionRunner>()
            .WithOnlyDiagnostics(EmptyNullableValueAccess.S3655)
            .WithBasePath(@"SymbolicExecution\Sonar")
            .WithConcurrentAnalysis(false);
```

2022-10-31 12:53 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/MethodParameterUnused.CSharp11.cs
> +        private void Argument_UsedInAttributeByNameOf(string argument) // Compliant, because this rule ignores methods that have attributes, not because of the nameof.
```suggestion
        private void Argument_UsedInAttributeByNameOf(string argument) // Compliant, methods with attributes are ignored
```

also below

2022-11-01 09:27 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2022-11-01 11:39 UTC, merged