Remove OldVerifier usage from tests D-E
SonarSource/sonar-dotnet pull request #6259
Opened 2022-10-31 08:54 UTC by csaba-sagi-sonarsource

2022-10-31 13:02 UTC, cristian-ambrosini-sonarsource requested changes
Just few things

2022-10-31 15:43 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotLockOnSharedResourceTest.cs
> +
See comment above

2022-10-31 16:20 UTC, cristian-ambrosini-sonarsource approved these changes

2022-11-01 10:28 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2022-11-01 10:29 UTC, merged