Add UTs for C#11 file-scoped types feature [rules a-c]
SonarSource/sonar-dotnet pull request #6270
Opened 2022-11-02 16:16 UTC by mary-georgiou-sonarsource

2022-11-03 20:28 UTC, costin-zaharia-sonarsource commented
I would add a test for `NonDerivedPrivateClassesShouldBeSealed`. I wonder if it brings any value to modify the rule and suggest to make sealed also the non-derived file-scoped types. The magic happens in `IsPrivateButNotSealedType`

2022-11-03 20:34 UTC, costin-zaharia-sonarsource commented
Could you please add tests also for: `TypeMemberVisibility` (https://rules.sonarsource.com/csharp/RSPEC-3059)

e.g.
```
file class Class1
{
    public void Method()
    {
```

2022-11-03 20:36 UTC, costin-zaharia-sonarsource requested changes

2022-11-03 20:36 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastConcreteTypeToInterface.CSharp11.cs
> +﻿using System;
I think we don't need tests for this. The rule subscribes only to cast and `AsIs` expressions and there are no scope-related checks.

2022-11-03 20:36 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ClassShouldNotBeAbstract.CSharp11.cs
> +﻿using System;
As far as I can tell, this rule does not check the type modifiers. I think it's enough to have one very simple noncompliant case and one compliant.

2022-11-04 08:33 UTC, mary-georgiou-sonarsource commented
> I would add a test for `NonDerivedPrivateClassesShouldBeSealed`. I wonder if it brings any value to modify the rule and suggest to make sealed also the non-derived file-scoped types. The magic happens in `IsPrivateButNotSealedType`

@costin-zaharia-sonarsource  File-scoped types have to be always top-level (cannot be nested) and they cannot also have access modifiers (cannot be private).

If they should be sealed in case they are not derived in the file where they are declared it's probably another rule. We can discuss if it worths creating one in case.

2022-11-04 09:04 UTC, costin-zaharia-sonarsource commented
> Based on the fact that file-scoped types are not visible outside the class and they cannot use accessibility modifiers do we need this? Am I missing something?

I would document the behavior since the rule description contains:
```
There’s no point in having a public member in a non-public type because objects that can’t access the type will never have the chance to access the member.
```

But indeed, I think the rule does not need to be changed.

2022-11-04 09:14 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/CastConcreteTypeToInterfaceTest.cs
> +
pedantic: can be removed

2022-11-04 09:14 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2022-11-04 10:23 UTC, merged