Fix an FP for S2933 (FieldShouldBeReadonly)
SonarSource/sonar-dotnet pull request #6317
Opened 2022-11-07 16:36 UTC by gregory-paidis-sonarsource

Fixes #6313

2022-11-08 08:53 UTC, cristian-ambrosini-sonarsource approved these changes
Great!

2022-11-11 12:57 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/FieldShouldBeReadonly.CSharp11.cs
NITPICK: Line 28 is not necessary.

2022-11-11 13:03 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/FieldShouldBeReadonly.cs
>          };
Please make `ReadonlyFieldCollector` and `PartialTypeDeclarationProcessor` classes sealed.

2022-11-11 13:04 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/FieldShouldBeReadonly.cs
>          {
On line 85 and 90. The two `if`s can be merged into one.

2022-11-11 13:04 UTC, csaba-sagi-sonarsource requested changes
Small cleanup changes requested.

2022-11-15 16:01 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-11-15 16:01 UTC, merged