S2688 FN: Do not raise for IsExpression since it works as expected
SonarSource/sonar-dotnet pull request #6348
Opened 2022-11-10 13:49 UTC by gregory-paidis-sonarsource

Fixes #6289

2022-11-10 13:51 UTC, gregory-paidis-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/CompareNaN.cs
> -            { KnownType.System_Byte, "byte" },
Removed some types from here, that do not have a `.NaN` property.

2022-11-14 10:54 UTC, cristian-ambrosini-sonarsource approved these changes

2022-11-15 16:05 UTC, csaba-sagi-sonarsource commented
Something is wrong with the Syntax.xml file. It has 9663 lines changed. Please take a look at what is the problem.

2022-11-15 16:54 UTC, gregory-paidis-sonarsource commented
> Something is wrong with the Syntax.xml file. It has 9663 lines changed. Please take a look at what is the problem.

Indeed, i reseted the changes locally and pushed with force the same commit, should be okay, please take a look again.

2022-11-15 17:02 UTC, csaba-sagi-sonarsource requested changes
I left a few comments, after addressing that it should be good to go!

2022-11-15 17:02 UTC, csaba-sagi-sonarsource commented
Please update the PR title to reflect that it is not going to fix the list pattern case it was not a FN.

2022-11-16 09:44 UTC, gregory-paidis-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
> +  <Node Name="ListPatternSyntax" Base="PatternSyntax">
you are correct, this remained from a previous implementation by mistake, same with the expression bodied method comment.

2022-11-16 11:20 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-11-17 08:18 UTC, merged