Support `Microsoft.Data.SqlClient` in S2857.
SonarSource/sonar-dotnet pull request #6351
Opened 2022-11-10 19:48 UTC by teo-tsirpanis

2022-12-19 08:44 UTC, martin-strecker-sonarsource commented
Related #6205

2022-12-21 15:00 UTC, martin-strecker-sonarsource requested changes

2022-12-21 15:00 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/SqlKeywordsDelimitedBySpace.cs
> +            CSharpSyntaxHelper.BuildQualifiedNameSyntax("Microsoft", "Data", "SqlClient"),
This needs to be covered by tests.

2022-12-21 15:00 UTC, martin-strecker-sonarsource commented
/azp run

2023-01-28 17:47 UTC, teo-tsirpanis commented on analyzers/src/SonarAnalyzer.CSharp/Rules/SqlKeywordsDelimitedBySpace.cs
> +            CSharpSyntaxHelper.BuildQualifiedNameSyntax("Microsoft", "Data", "SqlClient"),
Done.

2023-02-23 07:30 UTC, martin-strecker-sonarsource commented
/azp run

2023-02-23 08:30 UTC, martin-strecker-sonarsource approved these changes
LGTM. Thank you @teo-tsirpanis

2023-02-23 08:30 UTC, merged