Fix S3168 FN: Support virtual interface methods
SonarSource/sonar-dotnet pull request #6352
Opened 2022-11-11 08:18 UTC by cristian-ambrosini-sonarsource

Fixes #6305

2022-11-11 16:01 UTC, csaba-sagi-sonarsource commented
Please rename the issue and leave a comment why it is compliant.
Based on the issue title one would think it fixes an FN however it actually marks the "FN" compliant.

2022-11-11 16:05 UTC, csaba-sagi-sonarsource requested changes
One comment was left about the titles of the PR and issue.

2022-11-11 16:30 UTC, cristian-ambrosini-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AsyncVoidMethod.CSharp11.cs
> +        static virtual async void SomeVirtualMethod() // Compliant (virtual member)
The rule explicitly ignore abstract/virtual methods as the implementation in the class might end up being non-async.

2022-11-14 09:47 UTC, gregory-paidis-sonarsource approved these changes

2022-11-14 15:45 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-11-14 15:46 UTC, merged