Fix S2115 FN: Support multi-line string interpolation inside a raw string literal
SonarSource/sonar-dotnet pull request #6359
Opened 2022-11-14 13:12 UTC by cristian-ambrosini-sonarsource

Fixes #6293

2022-11-14 15:00 UTC, gregory-paidis-sonarsource commented
I added a minor change. I also see a hotspot issue raised by sonarcloud on line 169.

Apart from that, looks good to me!

2022-11-14 15:00 UTC, gregory-paidis-sonarsource requested changes

2022-11-14 16:22 UTC, gregory-paidis-sonarsource approved these changes

2022-11-15 14:30 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/DatabasePasswordsShouldBeSecure.cs
>          protected override void Initialize(TrackerInput input)
One really NITPICK comment: The Language  property from line 58 should go before the constructor

2022-11-15 14:35 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-11-15 15:37 UTC, merged