Fix S2934 FN: Support unsigned right shift operator (>>>)
SonarSource/sonar-dotnet pull request #6363
Opened 2022-11-15 13:18 UTC by gregory-paidis-sonarsource

Fixes #6296

2022-11-15 14:42 UTC, cristian-ambrosini-sonarsource requested changes
LGTM! I suggest to remove 1 line

2022-11-15 14:42 UTC, cristian-ambrosini-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
> +        public const SyntaxKind GreaterThanGreaterThanGreaterThanToken = (SyntaxKind)8286;
This is not used, maybe we can remove it to add less code as possible

2022-11-15 15:22 UTC, cristian-ambrosini-sonarsource approved these changes

2022-11-15 17:15 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/GenericReadonlyFieldPropertyAssignment.cs
> +                SyntaxKindEx.GreaterThanGreaterThanGreaterThanEqualsToken);
Use. At this point, registering to the token or the UnsignedRightShiftAssignmentExpression might give back the same syntax node but that might change in the future. This is the correct way to do it. (In a weird case that token can appear in other constructs too.)
```suggestion
                SyntaxKindEx.UnsignedRightShiftAssignmentExpression);
```

2022-11-15 17:16 UTC, csaba-sagi-sonarsource requested changes
Left a couple of comments.

2022-11-16 10:57 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-11-16 12:59 UTC, merged