S4790 FN: Edit test cases to const string, added interpolation test case
SonarSource/sonar-dotnet pull request #6364
Opened 2022-11-15 14:19 UTC by cristian-ambrosini-sonarsource

Fixes #6298

2022-11-16 16:43 UTC, gregory-paidis-sonarsource approved these changes

2022-11-16 18:48 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/CreatingHashAlgorithms.cs
> +            const string part1 = "System.Security.Cryptography";
Please also add a test case that documents that non-constant interpolated string values are not evaluated.

2022-11-16 18:50 UTC, csaba-sagi-sonarsource requested changes
Please add one more test case.

2022-11-17 08:48 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-11-17 08:49 UTC, merged