Add UTs for C#11 "new lines in interpolated strings" feature (non SonarWay rules)
SonarSource/sonar-dotnet pull request #6403
Opened 2022-11-21 13:31 UTC by mary-georgiou-sonarsource

2022-11-22 10:32 UTC, martin-strecker-sonarsource requested changes
In one test case "Noncompliant" and "Compliant" are mixed up.

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/NormalizeStringsToUppercaseTest.cs
> +            new VerifierBuilder<NormalizeStringsToUppercase>().AddPaths("NormalizeStringsToUppercase.CSharp11.cs")
The guide line for the VerifierBuilder is to create a field
```cs
private readonly VerifierBuilder builder = new VerifierBuilder<DatabasePasswordsShouldBeSecure>();
```
and use it in the tests.
```suggestion
            builder.AddPaths("NormalizeStringsToUppercase.CSharp11.cs")
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp11.cs
> +    static string GetName() => "Bar";
Needs at least 5 characters:
```suggestion
    static string GetName() => "BarBar";
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp11.cs
> +        GetName()
```suggestion
        "BarBar"
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp11.cs
> +        GetName()
```suggestion
        "BarBar"
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp11.cs
> +    public static string NameThree = "Bar"; // FN
```suggestion
    public static string NameThree = "BarBar"; // FN
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp11.cs
> +    public static readonly string NameReadonly = $"{GetName()}"; // FN
```suggestion
    public static readonly string NameReadonly = $"{"BarBar"}"; // FN
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOperationWithoutCulture.CSharp11.cs
> +                }} ".ToUpper(); // Noncompliant {{Define the locale to be used in this string operation.}}
```suggestion
                }}".ToUpper(); // Noncompliant {{Define the locale to be used in this string operation.}}
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOperationWithoutCulture.CSharp11.cs
> +using System.Linq.Expressions;
```suggestion
```

2022-11-22 10:32 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NormalizeStringsToUppercase.CSharp11.cs
> +            }}".ToLowerInvariant(); // Noncompliant
Noncompliant? According to StringOperationWithoutCulture.cs test cases, it is the other way around: `ToLowerInvariant` is compliant and `ToLower` is NonCompliant.

2022-11-22 11:04 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp11.cs
> +        GetName()
Thanks a lot for catching this. 🤦

2022-11-23 08:42 UTC, martin-strecker-sonarsource requested changes
One more VerfierBuilder and a small change in one test.

2022-11-23 08:42 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringOperationWithoutCultureTest.cs
> +            new VerifierBuilder<StringOperationWithoutCulture>().AddPaths("StringOperationWithoutCulture.CSharp11.cs")
Use `builder ` field

2022-11-23 08:42 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringLiteralShouldNotBeDuplicated.CSharp11.cs
> +        }";
Just to change the formatting a bit between the four assignments:

```suggestion
    public string NameTwo = $"{
            "BarBar" // Secondary
        }";
```

2022-11-23 15:48 UTC, martin-strecker-sonarsource approved these changes
LGTM

2022-11-23 15:48 UTC, merged