Fix S5122 FN: Support raw string literals interpolation
SonarSource/sonar-dotnet pull request #6410
Opened 2022-11-22 11:27 UTC by cristian-ambrosini-sonarsource

Fixes #6383

2022-11-24 14:47 UTC, gregory-paidis-sonarsource requested changes
LGTM, added a minor comment.

2022-11-24 14:47 UTC, gregory-paidis-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PermissiveCors.CSharp11.cs
> +            Response.Headers.Add($$"""{{part3}}-{{part4}}""", "*"); // Noncompliant
Maybe add some more testcases with raw "components", like the following:
```csharp
        const string part3 = """Access-Control""";
        const string part4 = """Allow-Origin""";
        Response.Headers.Add($$"""{{part3}}-{{part4}}""", "*"); // Noncompliant

        const string RawStar = """*""";
        Response.Headers.Add($$"""Access-Control-Allow-Origin""", RawStar); // Noncompliant
```

2022-11-24 15:51 UTC, gregory-paidis-sonarsource approved these changes

2022-11-25 17:44 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PermissiveCors.CSharp11.cs
> +            Response.Headers.Add($$"""{{constAccessControl}}-{{constAllowOrigin}}""", "*"); // Noncompliant
Could you please also add a C#10 test case where you create a constant interpolated string and pass that as an argument? That should also work, just to document the behavior.

2022-11-25 17:44 UTC, csaba-sagi-sonarsource requested changes
I suggested to add one more test case.

2022-11-28 15:23 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/PermissiveCors.CSharp10.cs
> +                const string constAllowOrigin = "Allow-Origin";
This test case is also good, and I suggest to add something else like:
```
const string constAccessControl = "Access-Control";
const string constAllowOrigin = "Allow-Origin";
const string interpolatedString = $"{constAccessControl}-{constAllowOrigin}";
Response.Headers.Add(interpolatedString , "*");
```

2022-11-28 15:24 UTC, csaba-sagi-sonarsource approved these changes
LGTM, I left one more comment to add another test case.

2022-11-29 08:07 UTC, merged