S3262 FN: Mark comments as compliant in UTs
SonarSource/sonar-dotnet pull request #6443
Opened 2022-11-25 13:57 UTC by gregory-paidis-sonarsource

Fixes #6389

2022-11-25 16:32 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM!

2022-11-25 17:33 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/MethodOverrideNoParams.cs
> -                    if (methodSymbol == null ||
Actually if you invert the conditions you can merge it with the if below which I think should increase the readability. WDYT?

2022-11-25 17:33 UTC, csaba-sagi-sonarsource requested changes
Left one Nitpick comment

2022-11-29 10:34 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/MethodOverrideNoParams.cs
> +                    && !method.ParameterList.Parameters.Last().Modifiers.Any(SyntaxKind.ParamsKeyword))
It should be indented with one more tab.

2022-11-29 10:34 UTC, csaba-sagi-sonarsource approved these changes
I approved with one indentation to fix. Please address it before merging.

2022-11-29 14:27 UTC, merged