S3440 FN: Add test cases for is expression
SonarSource/sonar-dotnet pull request #6445
Opened 2022-11-25 14:47 UTC by cristian-ambrosini-sonarsource

This PR is closing issue #6390 since it's not C#11 related, the test will remain marked as FN and another issue will be opened to address the 'is' and 'is not' expressions for this rule.

2022-11-25 15:03 UTC, cristian-ambrosini-sonarsource commented
Issue #6447 opened for fixing FN with 'is' and 'is not' expressions

2022-11-25 16:03 UTC, gregory-paidis-sonarsource approved these changes
LGTM!

2022-11-25 17:15 UTC, csaba-sagi-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/RedundantConditionalAroundAssignment.CSharp9.cs
> +        }
This is redundant, you have already added it to the base test cases.

2022-11-25 17:16 UTC, csaba-sagi-sonarsource requested changes
Left one small comment.

2022-11-28 16:05 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2022-11-28 16:05 UTC, merged