Fix S2068 FN: Support utf-8 string literals
SonarSource/sonar-dotnet pull request #6466
Opened 2022-11-29 17:17 UTC by mary-georgiou-sonarsource

Fixes #6394>

2022-11-30 13:00 UTC, martin-strecker-sonarsource requested changes
I think the GetStringValue override is not the right solution. It should be possible to do it one layer up in the inheritance chain.

2022-12-02 08:27 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Helpers/CsharpStringValueHelper.cs
> +            if (base.GetStringValue(node, semanticModel) is { } stringValue)
Merged!

2022-12-02 15:18 UTC, mary-georgiou-sonarsource commented
@martin-strecker-sonarsource please re-assign to @csaba-sagi-sonarsource after you review as I'll be away. 
We just synced on the matter.

2022-12-06 11:48 UTC, martin-strecker-sonarsource submitted a review, later dismissed
I'm taking the implementation over from Mary.

2022-12-07 15:43 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM!

2022-12-07 15:53 UTC, merged