Remove useless package references
SonarSource/sonar-dotnet pull request #6549
Opened 2022-12-15 11:52 UTC by cristian-ambrosini-sonarsource

Fixes #6511

2022-12-15 12:26 UTC, martin-strecker-sonarsource reviewed
We see a lot of downgrades. I think this is caused by the old version of Microsoft.CodeAnalysis.CSharp.Workspaces probably.

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "1.1.0",
Downgrade. Most likely caused by the old version of the analyzer Microsoft.CodeAnalysis.CSharp.Workspaces referenced.

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "1.0.1",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.0.11",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.0.11",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.1.0",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.1.0",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.0.1",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.0.1",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.1.0",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.1.0",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.0.11",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.1.0",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.0.11",
Downgrade

2022-12-15 12:26 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/packages.lock.json
> +        "resolved": "4.0.11",
Downgrade

2022-12-15 13:29 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
> -    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
This ensures that we use the latest version of `RegularExpressions` also while building the project. 

If there really are vulnerabilities in the old version, this ensures that the vulnerability is not exploited while building the project and running the tests.

What is the alternative to mitigate that?

2022-12-15 13:31 UTC, costin-zaharia-sonarsource requested changes
See my comment about removing the package reference.

2022-12-15 14:38 UTC, cristian-ambrosini-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
> -    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
In all honesty, I wasn't aware that a vulnerability could be exploited during the build process. If this is the case and I understood it correctly the problem extends also to the other packages as well (System.Net.Http and System.IO.FileSystem), right? And probably the whole PR/issue can be closed leaving the references as is

2022-12-15 17:34 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
> -    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
> What is the alternative to mitigate that?

Keeping our Laptops and CI images up-to-date is the only way I can think of. I don't see how we are exploitable because we fully control the input and the pattern of the regex executed during the tests.

2022-12-16 14:41 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
> -    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
I also think that the risk is very low with this library considering how we use it. At the same time, we restore what is linked, and in this case, it will be an old version. I think that keeping the laptop and CI up to date is not helping if the restored package is old.

2023-01-03 13:54 UTC, costin-zaharia-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.csproj
> -    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
We had a discussion earlier about this and we decided to remove the reference for 2 reasons:
- the users are not affected by the change since the compiler will load the version already present on the user machine (as before)
- on our test pipeline, we have control of the data and the usage so there is no risk

2023-01-03 13:55 UTC, costin-zaharia-sonarsource approved these changes
LGTM!

2023-01-03 15:38 UTC, merged