Refactor SonarAnalysisContext - Bump coverage
SonarSource/sonar-dotnet pull request #6589
Opened 2022-12-23 09:40 UTC by pavel-mikula-sonarsource

Bump coverage for #6532

2023-01-04 16:28 UTC, costin-zaharia-sonarsource requested changes

2023-01-04 16:28 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSyntaxTreeAnalysisContextTest.cs
> +        sut.Cancel.Should().Be(cancel);
Options are missing also from here

2023-01-04 16:28 UTC, costin-zaharia-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SonarAnalysisContextExtensionsTest.cs
> +    public TestContext TestContext { get; set; }
not used

2023-01-11 12:35 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarCompilationAnalysisContextTest.cs
> +        sut.Compilation.Should().Be(model.Compilation);
I was adding mostly those that were not covered.. I'll add them all

2023-01-13 08:07 UTC, costin-zaharia-sonarsource approved these changes
LGTM! Tests will be automatically fixed after rebase.

2023-01-16 13:21 UTC, merged