S4457 False positive when argument check is after async code Repro+Fix
SonarSource/sonar-dotnet pull request #6624
Opened 2023-01-12 13:29 UTC by gregory-paidis-sonarsource

Fixes #6449

2023-01-12 13:58 UTC, gregory-paidis-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInMethodWalker.cs
> +            else
Without this `else` block, the visit recursion stops for this node. 
This means that for something like:
```csharp
whatever.Invocation()
```
The `whatever.Invocation` syntax node is not going to keep visiting inside the `whatever` node, in which case if `whatever` contains an `AwaitExpression`, we will not spot it to stop the SyntaxWalker via:
```csharp
public override void VisitAwaitExpression(AwaitExpressionSyntax node) =>keepWalking = false;
```
Which produces this the FP in the testcases.

2023-01-23 13:25 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInMethodWalker.cs
>              {
This whole class is actually a helper and not a rule, so I suggest moving it to helpers.

2023-01-23 13:27 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInMethodWalker.cs
> +            else
Nitpick and completely optional, as you will "work" on `ParameterValidationInYieldShouldBeWrapped` by adding test cases I would also clean up the implementation of the rule while you have the context.

2023-01-23 13:28 UTC, csaba-sagi-sonarsource requested changes
A few more modifications requested

2023-01-25 16:40 UTC, gregory-paidis-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInMethodWalker.cs
> +                DefaultVisit(node);
good catch, I missed that :(

2023-01-26 14:59 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInAsyncShouldBeWrapped.cs
> +            public ParameterValidationInAsyncWalker(SemanticModel semanticModel)
NITPICK:
```suggestion
            public ParameterValidationInAsyncWalker(SemanticModel semanticModel) : base(semanticModel) { }
```

2023-01-26 15:00 UTC, csaba-sagi-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ParameterValidationInYieldShouldBeWrapped.cs
> +        private sealed class ParameterValidationInYieldWalker : ParameterValidationInMethodWalker
NITPICK:
The constructor could be in a single line.

2023-01-26 15:22 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2023-01-26 15:22 UTC, merged