Wildcard pattern matcher improvement
SonarSource/sonar-dotnet pull request #6919
Opened 2023-03-13 15:02 UTC by cristian-ambrosini-sonarsource

This PR aims to address the comments on the WildcardPatternMatcher, see [feature branch PR](https://github.com/SonarSource/sonar-dotnet/pull/6870).

2023-03-15 11:08 UTC, pavel-mikula-sonarsource requested changes
Some more polishing

2023-03-15 11:08 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
This empty line doesn't help
```suggestion
```

2023-03-15 11:08 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
>                      // Single character
Doesn't help.
Same for the "Directory separator" above
```suggestion
```

2023-03-15 11:08 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +            return sb.Append('$').ToString();
`WildcardPatternMatcherTest.cs`: Empty lines between `DataRows` is very hard to read

2023-03-15 11:08 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +            return sb.Append('$').ToString();
`WildcardPatternMatcherTest.cs`: It's weird to use `.java` instead of `.cs`

2023-03-15 11:08 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
>                          // Zero or more characters excluding directory separator
Can be merged to a single line. 
Also above with the double
```suggestion
                        // Single asterisk - Zero or more characters excluding directory separator
```

2023-03-15 13:08 UTC, cristian-ambrosini-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
>          public bool Match(string value)
This way it triggers a [S3218](https://rules.sonarsource.com/csharp/RSPEC-3218).

2023-03-15 14:00 UTC, cristian-ambrosini-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +            Cache.GetOrAdd(pattern + Path.DirectorySeparatorChar, _ => new WildcardPattern(pattern));
The directory separator is part of the resulting regular expression, thus changing the platform will produce a different Regex. Having both the pattern and the separator as a key of the dictionary will force recalculating the new Regex for the new platform. Is that right?

2023-03-15 14:21 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +            Cache.GetOrAdd(pattern + Path.DirectorySeparatorChar, _ => new WildcardPattern(pattern));
Your statement is technically correct.

Is the code correct?

2023-03-15 14:22 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
>          private static readonly ConcurrentDictionary<string, WildcardPattern> Cache = new();
I just wanted to make sure that this aspect of behavior is known and intentional.

2023-03-15 14:23 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +        private WildcardPattern(string pattern) =>
This is not completely what I meant. The question was: Do we really need two classes? One should do the trick.

2023-03-15 14:24 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
>          public bool Match(string value)
That should get fixed by removing `WildcardPattern` class

2023-03-15 14:27 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +    public static bool IsMatch(string pattern, string input, bool timoutFallback = false) =>
I'd add `Result` to the name, as `timeoutFallback` isn't clear enough. Even when I usually prefer shorter names.
I'd not give it a default value. It is used twice, each time with different value.
```suggestion
    public static bool IsMatch(string pattern, string input, bool timoutFallbackResult) =>
```

2023-03-15 15:12 UTC, cristian-ambrosini-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +        private WildcardPattern(string pattern) =>
Ok sorry, I misread your comment, I think now I got it.

2023-03-15 15:48 UTC, pavel-mikula-sonarsource approved these changes
LGTM, remove the Path.DirectorySeparatorChar before merging from the last unresolved conversation

2023-03-15 15:54 UTC, cristian-ambrosini-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +            Cache.GetOrAdd(pattern + Path.DirectorySeparatorChar, _ => new WildcardPattern(pattern));
Do you mean that the platform will remain the same so there is no need to store that information as a key?

2023-03-16 07:32 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
> +            Cache.GetOrAdd(pattern + Path.DirectorySeparatorChar, _ => new WildcardPattern(pattern));
Exactly.

2023-03-16 07:32 UTC, merged