SE - Property reference: Test case for auto properties are not learning constraints
SonarSource/sonar-dotnet pull request #6931
Opened 2023-03-15 09:51 UTC by martin-strecker-sonarsource

Test case for #6930

2023-03-15 13:44 UTC, pavel-mikula-sonarsource requested changes
We'll eventually need tests for `IOperationExtensionsTest`. Are those going to be part of the implementation later?

2023-03-15 13:44 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +                public object AutoProperty { get; set; }
What about moving this into `SETestContext` with the others, like `Property`?

2023-03-15 13:44 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +        public void PropertyReference_NotTrackedFor_FullProperties()
To explain the context and then say the expectations
```suggestion
        public void PropertyReference_FullProperties_NotTracked()
```

2023-03-15 13:46 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +            validator.ValidateTag("AfterSetNull", x => x.Should().HaveNoConstraints()); // FN Auto-properties should behave the same as fields. Expected: HaveOnlyConstraint(ObjectConstraint.Null)
Education: What is the difference between FN and FIXME in this context?

2023-03-16 07:57 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
> +            validator.ValidateTag("AfterSetNull", x => x.Should().HaveNoConstraints()); // FN Auto-properties should behave the same as fields. Expected: HaveOnlyConstraint(ObjectConstraint.Null)
@Tim-Pohlmann 
Technically it's not FN, as there are no issues involved related to any rule. It's just incorrect behavior of some part of the code.

`FIXME` should never make it to `master` and must be addressed before the feature branch is merged. It is tracked by S1134.
`ToDo` could make it to master and be done later. It is tracked by S1135.

2023-03-16 12:46 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2023-03-16 12:46 UTC, merged