SE: Enumerable ContentHash
SonarSource/sonar-dotnet pull request #6979
Opened 2023-03-23 11:03 UTC by martin-strecker-sonarsource

Part of #6964

2023-03-23 13:42 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs
> +#pragma warning disable CA1825 // Avoid zero-length array allocations
I'd be fine with disabling this at the beginning of this file once. And not enabling it.

2023-03-23 13:43 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
> +        private const int IntSeed = 393241;
This is givin "Empty" some random value? Why not keeping `0` for empy? It's valid integer has value like any other

2023-03-23 13:44 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
> +            enumerable.Aggregate(IntSeed, Combine);
For these two, I'd consider single-line documentation comments that will explain the different usage.

2023-03-24 14:25 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
> +        private const int IntSeed = 393241;
I need answers to these questions before approving.

2023-03-24 14:25 UTC, pavel-mikula-sonarsource requested changes
There was one missed thread above that needs answers, or to be addressed

2023-03-27 08:34 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
> +        private const int IntSeed = 393241;
Damit! Always the same mistake:
![image](https://user-images.githubusercontent.com/103252490/227887230-d9076fbb-07f4-41ca-aa94-d6ed68771dd2.png)

2023-03-27 09:46 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2023-03-27 09:46 UTC, merged