S3655: Test mutable fields with methods, local functions, yield and async
SonarSource/sonar-dotnet pull request #6981
Opened 2023-03-23 13:22 UTC by antonioaversa

Part 3 of task 6 of https://github.com/SonarSource/sonar-dotnet/issues/6794

Previous task: https://github.com/SonarSource/sonar-dotnet/pull/6967

2023-03-24 14:47 UTC, Tim-Pohlmann requested changes

2023-03-24 14:47 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
> +        _ = theField.Value;          // Compliant, when reached the ".Value" above implies aField is not null
```suggestion
        _ = theField.Value;          // Compliant, when reached the ".Value" above implies theField is not null
```

2023-03-27 08:33 UTC, Tim-Pohlmann approved these changes

2023-03-27 10:46 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2023-03-27 10:46 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
> +        _ = theField.Value;          // Compliant, yield break above stops execution
Here you can use "unreachable" 😄

2023-03-28 15:27 UTC, merged