SE: S3900 FP: Don't raise if parameter is captured
SonarSource/sonar-dotnet pull request #7065
Opened 2023-04-13 11:17 UTC by martin-strecker-sonarsource

Suppresses FP reported in #7060

Captured Symbols are removed prematurely from the state. Until this is fixed, we need to suppress the reporting of S3900.

2023-04-13 13:53 UTC, martin-strecker-sonarsource commented on analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S3900.json
> -"uri":  "sources\Ember-MM\Addons\scraper.EmberCore.XML\XMLScraper\ScraperXML\ScraperManager.vb",
https://github.com/SonarSource/sonar-dotnet/blob/fa201ae2d8fc9e264d558cc31bf9e82116a59a23/analyzers/its/sources/Ember-MM/Addons/scraper.EmberCore.XML/XMLScraper/ScraperXML/ScraperManager.vb#L168

2023-04-13 13:54 UTC, martin-strecker-sonarsource commented on analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S3900.json
> -"uri":  "sources\Ember-MM\Addons\generic.EmberCore.NMT\dlgNMTMovies.vb",
Looks good
https://github.com/SonarSource/sonar-dotnet/blob/fa201ae2d8fc9e264d558cc31bf9e82116a59a23/analyzers/its/sources/Ember-MM/Addons/generic.EmberCore.NMT/dlgNMTMovies.vb#L548

2023-04-13 13:56 UTC, martin-strecker-sonarsource commented on analyzers/its/expected/Nancy/Nancy--net452-S3900.json
> -"startLine":  123,
Looks good
https://github.com/SonarSource/sonar-dotnet/blob/40039103f8b52ccc659266cb2092c621b6ec482d/analyzers/its/sources/Nancy/src/Nancy/AfterPipeline.cs#L121-L127

2023-04-13 15:04 UTC, pavel-mikula-sonarsource requested changes
Let's give it the LVA itself.

2023-04-14 06:21 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
> +        public IReadOnlyCollection<ISymbol> CapturedVariables { get; }
Ah, that's an overkill then :/ I thought it would be simple. 

Let's roll back to you original solution.

2023-04-14 07:07 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
> +        public IReadOnlyCollection<ISymbol> CapturedVariables { get; }
D'accord. All solutions I could come up with were worse than the original.

2023-04-14 07:11 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2023-04-14 07:11 UTC, merged

2023-04-17 11:29 UTC, martin-strecker-sonarsource commented
Peach validation: This PR produces tons of FNs. I could not find any FPs being removed, but I didn't look for it (I just confirmed that the removal was caused by a capture somewhere but didn't confirm FP/TP classification thoroughly).