TokenTypeAnalyzer: Create a DSL for token type analyzer
SonarSource/sonar-dotnet pull request #7108
Opened 2023-04-24 15:53 UTC by martin-strecker-sonarsource

Fix #7289
The tests for the TokenTypeAnalyzer could be more precise. They only assert the number of tokens per type found in a code snippet. We need a more precise way to assert the token type. The best way is to annotate the code snippet with the expected token type and position. This PR adds a small test harness with support for `[x:SomeToken]` syntax, where x corresponds to the TokenType enum defined by the protobuf contract like so:
* k = Keyword
* n = NumericLiteral
* s = StringLiteral
* t = TypeName
* c = Comment
* u = UnknownTokentype

A code snippet like
```cs
public class Test
{
}
```
can be annotated and asserted like so:
```cs
public [k:class] [t:Test]
{
}
```

2023-05-19 09:23 UTC, martin-strecker-sonarsource commented
I oppose the changes in [3faa20c](https://github.com/SonarSource/sonar-dotnet/pull/7108/commits/3faa20cce95be2ac522216bc877c753c2045bf70). We look at the parent node, but the node, in theory, can have more than one identifier token property. So the parent of a token doesn't guarantee that the identifier token is the one we expect. We should be explicit about it. Consider this contrived example:
```cs
class ClassDeclarationSyntaxNode: SyntaxNode
{
  public SyntaxToken ClassName { get; } // Considered a type
  public SyntaxToken SomeIdentifierAddedInSomeFutureLanguageVersion { get; } // Not considered a type
}
```
Both `SyntaxToken` are IdentifierToken and have the same parent, but only one is considered to be a type. To be more robust for future language changes, we should be explicit about the position the IdentifierToken has to be present in the Node.
This is one of the cases where we should ignore the code coverage violation as this is more robust but untestable code (For some of the SyntaxNodes, you might be able to create an instance with the SyntaxFactory where you pass an "IdentiferToken," e.g., at a parenthesizes position, but as far as I remember  SyntaxFactory throws if you try to do something like this.).

2023-05-19 09:48 UTC, csaba-sagi-sonarsource commented
> I oppose the changes in [3faa20c](https://github.com/SonarSource/sonar-dotnet/pull/7108/commits/3faa20cce95be2ac522216bc877c753c2045bf70). We look at the parent node, but the node, in theory, can have more than one identifier token property. So the parent of a token doesn't guarantee that the identifier token is the one we expect. We should be explicit about it. Consider this contrived example:
> 
> ```cs
> class ClassDeclarationSyntaxNode: SyntaxNode
> {
>   public SyntaxToken ClassName { get; } // Considered a type
>   public SyntaxToken SomeIdentifierAddedInSomeFutureLanguageVersion { get; } // Not considered a type
> }
> ```
> 
> Both `SyntaxToken` are IdentifierToken and have the same parent, but only one is considered to be a type. To be more robust for future language changes, we should be explicit about the position the IdentifierToken has to be present in the Node. This is one of the cases where we should ignore the code coverage violation as this is more robust but untestable code (For some of the SyntaxNodes, you might be able to create an instance with the SyntaxFactory where you pass an "IdentiferToken," e.g., at a parenthesizes position, but as far as I remember SyntaxFactory throws if you try to do something like this.).

If such a future addition would be anything but an identifier, it would be already classified [here](https://github.com/SonarSource/sonar-dotnet/blob/924f944236830c8db05f10f308333c040c649be1/analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs#L121).
Now if the construct would have 2 identifiers, the worst thing that could happen is we don't colour that one properly (there would be no AD0001). I think we could handle such future changes when the new language version comes out, like we add support for new syntax in any other rule. WDYT?

2023-05-19 10:25 UTC, martin-strecker-sonarsource commented
For me, it is a matter of correctness. Now, you say: "Whatever identifier token is directly in a class declaration is classified as a type." What was said before was: "The identifier token must be in a class declaration at the `Identifier` position." The second sentence is the correct one, easier to understand for the reader, and more robust. It is funny how I always have to fight for more robust code - which is often untestable - because we have a "quality gate" that regularly forces us to introduce less robust code. I, e.g., often removed some null-checking code on demand in the past because of that.

2023-05-19 13:08 UTC, csaba-sagi-sonarsource commented
I have pinged @pavel-mikula-sonarsource  to take a look and see his opinion.
I am not entirely convinced. I mean if a new syntax is added back, it will fall back to the base call and if the new syntax is not covered there (the chances are high that it is not) It will have the same behaviour, as now without the checks.

2023-05-19 13:44 UTC, martin-strecker-sonarsource commented
> I mean if a new syntax is added back, it will fall back to the base call

Just to avoid confusion: It is the opposite way around. With your change, the fallback to the base call will not happen. The new token is falsely classified because you removed the additional `when` check that caused the fallback to happen before.

2023-05-19 14:05 UTC, mary-georgiou-sonarsource requested changes
Round 1

2023-05-19 14:05 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.ClassifierTestHarness.cs
> +                    }
I would extract the action given to the `SatisfyRespectively` in another method or local function - otherwise, I find it very confusing.

2023-05-19 14:09 UTC, csaba-sagi-sonarsource commented
> > I mean if a new syntax is added back, it will fall back to the base call
> 
> Just to avoid confusion: It is the opposite way around. With your change, the fallback to the base call will not happen. The new token is falsely classified because you removed the additional `when` check that caused the fallback to happen before. The fallback goes through the semantic model and does the classification based on symbols and so chances are high that the fallback does the right thing.

What I wanted to say, I might have not been the most precise ever. The base class will not know anything about the new syntax too and will return null. Like it is now.

2023-05-19 14:15 UTC, martin-strecker-sonarsource commented
> The base class will not know anything about the new syntax too and will return null. Like it is now.

No. `base.ClassifyIdentifier(token)` will query `semanticModel.GetDeclaredSymbol(token.Parent)` and `semanticModel.GetSymbolInfo` and will classify the symbol returned by it.

2023-05-19 14:20 UTC, csaba-sagi-sonarsource commented
> > The base class will not know anything about the new syntax too and will return null. Like it is now.
> 
> No. `base.ClassifyIdentifier(token)` will query `semanticModel.GetDeclaredSymbol(token.Parent)` and `semanticModel.GetSymbolInfo` and will classify the symbol returned by it.

If that is the case, otherwise it will return null.

2023-05-19 15:01 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
> +                    DestructorDeclarationSyntax => TokenInfo(token, TokenType.TypeName),
For some reasons I missed [AttributeTargetSpecifierSyntax.Identifier](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.attributetargetspecifiersyntax.identifier?view=roslyn-dotnet-4.6.0#microsoft-codeanalysis-csharp-syntax-attributetargetspecifiersyntax-identifier).

2023-05-26 13:33 UTC, closed without merging

2023-05-26 13:33 UTC, mary-georgiou-sonarsource commented
Closing for now - to be continued in a future sprint.

2023-08-04 11:14 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
> +                    DestructorDeclarationSyntax => TokenInfo(token, TokenType.TypeName),
Might all be parsed as keywords. A list of valid attribute targets is 

* assembly
* module
* event
* field
* method
* param
* property
* return
* type
* typevar

2023-08-04 12:50 UTC, martin-strecker-sonarsource commented
Continuation #7726