Implement S3949 logic
SonarSource/sonar-dotnet pull request #7221
Opened 2023-05-17 11:42 UTC by Tim-Pohlmann

Part of #4631

2023-05-22 07:12 UTC, pavel-mikula-sonarsource requested changes
Waaay nicer code than whatever the old implementation had to have :D

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
> +    private static SymbolicValue CanOverflow(ProgramState state, IOperation operation) => operation.Kind switch
I initially wanted to return operation, but that's not possible due to the tricky post increment/decrement :/
So let's give it a better name, as `CanOverflow` answer a question that should return `bool`.

```suggestion
    private static SymbolicValue OverflowCandidateValue(ProgramState state, IOperation operation) => operation.Kind switch
```
or
```suggestion
    private static SymbolicValue OverflowValue(ProgramState state, IOperation operation) => operation.Kind switch
```
or something like that

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
> +    private static SymbolicValue CanOverflow(ProgramState state, IOperation operation) => operation.Kind switch
EOL Formatting
```suggestion
    private static SymbolicValue CanOverflow(ProgramState state, IOperation operation) => 
        operation.Kind switch
```

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
> +    private static BigInteger? Min(ITypeSymbol type) => type switch
EOL formatting
```suggestion
    private static BigInteger? Min(ITypeSymbol type) => 
        type switch
```

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
> +    private static BigInteger? Min(ITypeSymbol type) => type switch
Also below

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
> +                ReportIssue(operation, MessageGuaranteed, MessageUnderflow, typeMax);
All message variants needs to be asserted
```suggestion
                ReportIssue(operation, MessageGuaranteed, MessageUnderflow, typeMin);
```

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
> +                ReportIssue(operation, MessageLikely, MessageUnderflow, typeMax);
All message variants needs to be asserted
```suggestion
                ReportIssue(operation, MessageLikely, MessageUnderflow, typeMin);
```

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
> +                int i = 1834567890 + 1834567890;    // Noncompliant
```suggestion
                int i = 1834567890 + 1834567890;    // Noncompliant FP, we don't want to run for methods with unchecked
```

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
> +    public void Upcast()
There should be few UTs with
```
var i = Unknown();
if(i > 2147483600)
  _ = i + 100; // Noncompliant
```

2023-05-22 07:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
> +        _ = i * 100;            // Noncompliant FIXME wrong reason, i doesn't change because compoundassignment is ignored
#7223 is already in review to fix this. 
Once merged, I'd rebase feature branch. And then you can rebase this PR.

2023-05-22 10:40 UTC, Tim-Pohlmann commented on analyzers/its/expected/Net7/Net7--net7.0-S3949.json
> +},
FN, unchecked keyword

2023-05-22 10:42 UTC, Tim-Pohlmann commented on analyzers/its/expected/Net7/Net7--net7.0-S3949.json
FNs, unchecked keyword

2023-05-22 10:42 UTC, Tim-Pohlmann commented on analyzers/its/expected/akka.net/Akka--netstandard2.0-S3949.json
FN, GetHashCode/unchecked keyword

2023-05-23 07:24 UTC, pavel-mikula-sonarsource commented on analyzers/its/expected/Net7/Net7--net7.0-S3949.json
FP instead of FN?

2023-05-23 07:25 UTC, pavel-mikula-sonarsource commented on analyzers/its/expected/akka.net/Akka--netstandard2.0-S3949.json
FP

2023-05-23 07:32 UTC, Tim-Pohlmann commented on analyzers/its/expected/akka.net/Akka--netstandard2.0-S3949.json
yes, mb!

2023-05-23 09:06 UTC, pavel-mikula-sonarsource approved these changes
LGTM, pleae rebase on feature branch to fix the compound cases in a new commit

2023-05-23 12:05 UTC, merged