Extend UnitTestHelper with IsIgnoredTestMethod
SonarSource/sonar-dotnet pull request #7333
Opened 2023-06-02 15:02 UTC by Corniel

As discussed in #6185, some extended unit test detection logic should be centralized.

2023-06-02 15:03 UTC, Corniel commented
@pavel-mikula-sonarsource  As this involves changing so three existing rules, I decided to make a small separate PR.

2023-06-05 08:28 UTC, Corniel commented
@pavel-mikula-sonarsource 

What about changing the API to: `IsTestMethod(bool includeIgnoredTests: false)`?

2023-06-25 12:49 UTC, Corniel commented
@pavel-mikula-sonarsource Any ETA on this?

2023-07-14 12:17 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
> +    private static bool IsMsTestOrNUnitTestIgnored(this IMethodSymbol method) =>
To match the logic of the field that it depends on
```suggestion
    private static bool HasIgnoredAttribute(this IMethodSymbol method) =>
```

2023-07-14 12:17 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
> +        method.IsMsTestOrNUnitTestIgnored()
```suggestion
        method.HasIgnoredAttribute()
```

2023-07-14 12:18 UTC, pavel-mikula-sonarsource commented
/azp run

2023-07-14 12:19 UTC, pavel-mikula-sonarsource commented
I'd keep the API as is. It's not use that often

2023-07-14 12:19 UTC, pavel-mikula-sonarsource commented
I'm sorry, we don't give ETAs in general. And I tend to be pretty busy all the time :)

2023-07-14 12:21 UTC, pavel-mikula-sonarsource commented
There's some infra issue with running CI :/

2023-07-14 12:26 UTC, pavel-mikula-sonarsource commented
Changes looks good, I'll need to run CI to verify the results.

2023-07-17 11:04 UTC, pavel-mikula-sonarsource commented
/azp run

2023-07-24 06:32 UTC, pavel-mikula-sonarsource commented
/azp run

2023-07-24 07:09 UTC, pavel-mikula-sonarsource requested changes
We'll need to fix the UTs :)
We did quite some changes on Java ITs - rebase could fix those.
Then I can take care of .NET ITs.

2023-07-30 07:09 UTC, Corniel commented
Did a rebase.

2023-08-21 11:23 UTC, Corniel commented
Another rebase.

2023-12-22 16:19 UTC, pavel-mikula-sonarsource commented
/azp run

2024-03-19 13:15 UTC, Corniel commented
another rebase.

2024-03-19 16:21 UTC, pavel-mikula-sonarsource commented
@Corniel Can you take a look at the UTs? They were failing during the previous run and I haven't seen a change there

2024-03-19 20:06 UTC, Corniel commented
@pavel-mikula-sonarsource The `regression-test.ps1` is gone?! Besides that, the setup still requires some environment variables that would not like to configure on my work laptop.

2025-03-08 08:06 UTC, Corniel commented
Due to the changes in the repo, I can not build stuff locally anymore. I close this one.

2025-03-08 08:06 UTC, closed without merging

2025-03-10 12:48 UTC, pavel-mikula-sonarsource commented
Hi, 
in case you're interested in recreating this PR, the `UnitTestHelper.cs` is gone and `IsIgnoredTestMethod` should be added to [SonarAnalyzer.Core/Semantics/Extensions/IMethodSymbolExtensions.cs](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Core/Semantics/Extensions/IMethodSymbolExtensions.cs)

Otherwise:

Yes, `regression-test.ps1` is gone. We've moved our ITs to internal QA pipeline that is not in this repo. From your point of view, there's one less thing to care about, as running ITs was close to impossible anyway for external PRs.

Which variable concerns you? If I remember correctly, we did not add or remove any recently. From my point of view, we have way too many of them and I'd like to reduce that in the future.

One thing that is problematic to build the project outside our environment is the `NuGet.config` file. We've added this to the [contributing-analyzer.md](https://github.com/SonarSource/sonar-dotnet/blob/master/docs/contributing-analyzer.md):

>Before following any of the guides below, if you are external contributor you need to delete analyzers\NuGet.Config.

Other than that, it should be buildable and testable locally. What's the problem you're facing?

2025-03-10 13:10 UTC, Corniel commented
Well, I can not build anymore due to other restrictions introduced. I've to log on to repox.jfrog.io, for which I obvioulsy have no credentials.

2025-03-10 13:20 UTC, pavel-mikula-sonarsource commented
That's why you need to delete `analyzers\NuGet.Config` file. Than your build will use the usual nuget.org package source

2025-03-10 13:29 UTC, Corniel commented
I now. But that is annoying. it also makes that creating PR's is more effort: I've continually have to revert and redo the deletion. I like working on this repo, but as long as this is required, I'll do no further contributions.

2025-03-10 15:00 UTC, pavel-mikula-sonarsource commented
We're unfortunately required to use authenticated calls via jfrog.io, so we can't change that. 

I case you'd have a better idea how to solve this (having local VS builds picking up this special nuget.config file by default while for external PRs have a mechanism to ignore it), we'd like to know.

2025-03-10 18:57 UTC, Corniel commented
@pavel-mikula-sonarsource I understand that you can't change that.

I do not have a better idea. Removing the `nuget.config` would be helping me, but would make the live of all of you obviously worse. Unless you only need this settings on dev environments of Sonar employees, than you could remove it and make it part of your root setup. (I can think of scenario's were that is will not fly on other reasons).

I could not found anything that makes it conditional once its on disk.

2025-03-11 07:08 UTC, pavel-mikula-sonarsource commented
Based on this conversation, a possible idea came to my mind. I'll need to check few things to verify if it would work. I'll let you know

2025-06-20 10:51 UTC, pavel-mikula-sonarsource commented
Hi @Corniel,

I've managed to update the repo into a state where `NuGet.Config` should no longer get into your way when working with it.

Please give it a try.

2025-06-30 13:29 UTC, Corniel commented
@pavel-mikula-sonarsource It seems to work. There have been *some* refactoring in the meantime, hopefully, This still is a desired improvement.