Create Scaffolding for S4158
SonarSource/sonar-dotnet pull request #7341
Opened 2023-06-06 12:14 UTC by Tim-Pohlmann

Part of #7300

2023-06-07 09:30 UTC, mary-georgiou-sonarsource reviewed
Couple of nitpicks

2023-06-07 09:34 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
> +        .WithConcurrentAnalysis(false);
I don't know. I did not touch this line.

2023-06-07 11:12 UTC, pavel-mikula-sonarsource requested changes
I wasn't able to review the basic test file :/

2023-06-07 11:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
> +        .WithConcurrentAnalysis(false);
Because the old SE uses lovely design with some shared state and that was causing troubles. Let's politely ignore this and leave it as it was

2023-06-07 11:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> +        public void DefaultConstructor()
This file is too difficult to review. I can't tell what changes are improvements and what changes are mistakes lost during the migration.

The intention of scaffolding was to have a file as similar as possible to the old one (except namespace, FIXMEs, C# 8 extraction and maybe removal of irrelevant blocks). 
And than somewhere else, like the implementation PR, have a clearly distinguished improvements visible.

2023-06-07 11:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
> +{
Should go away (in this PR - easy to review). It's just a useless scaffolding noise
```suggestion
```

2023-06-07 11:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp11.cs
> +public class Tests
Same here
```suggestion
public class Sample
```

2023-06-07 11:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
> +    }
There was a test case removed from here. Only the comment should have been replaced with FN
```
        list = new List<int>();
        list.Clear();   // FN, can't build CFG for this method
```

2023-06-07 11:12 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
> +        collection2.Clear();    // Non-compliant
As it was not detected by the old engine
```suggestion
        collection2.Clear();    // FN
```

2023-06-08 09:16 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
> +using SonarAnalyzer.Common;
Already merged, rebase should let this one go away. It's also fine to do it in the implementation PR (depends on the timing)

2023-06-08 09:27 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2023-06-08 09:28 UTC, merged