Fix S2077 FN: Add support for Mono.Data.Sqlite
SonarSource/sonar-dotnet pull request #7466
Opened 2023-06-19 11:33 UTC by martin-strecker-sonarsource

Fixes #7261

2023-06-19 15:22 UTC, Tim-Pohlmann requested changes
There are a few overloads that still need to be covered.

2023-06-19 15:22 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.Net46.MonoSqlLite.cs
> +{
Remove the namespace, kill the noise.

2023-06-19 15:22 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.Net46.MonoSqlLite.cs
> +    public class C
Maybe rename the class to `Sample` for consistency with other tests. `C` looks pretty arbitrary and confusing.

2023-06-19 15:22 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.Net46.MonoSqlLite.cs
> +            var adapter = new SqliteDataAdapter(string.Concat(query, parameters), connection);          // Noncompliant
Add a test for the overload taking `(string, string)`.

2023-06-19 15:22 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.Net46.MonoSqlLite.cs
> +            command = new SqliteCommand($"SELECT * FROM mytable WHERE mycol={query}");                  // Noncompliant
Add a UT for the overload taking `(string, SQLiteTransaction)`.

2023-06-19 15:22 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.Net46.MonoSqlLite.vb
> +            Dim adapter = New SqliteDataAdapter(String.Concat(query, parameters), connection)         ' Noncompliant
Add tests for the overloads mentioned in the C# UT.

2023-06-19 15:22 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.Net46.MonoSqlLite.vb
> +    Public Class C
Remove the namespace, rename the class. Same as for C#.

2023-06-20 08:36 UTC, Tim-Pohlmann approved these changes
I just realized you should also add compliant test cases for unformatted strings (literal or variable).
Everything else LGTM.

2023-06-20 09:45 UTC, martin-strecker-sonarsource commented
> I just realized you should also add compliant test cases for unformatted strings (literal or variable).

There is https://github.com/SonarSource/sonar-dotnet/blob/2197ff3c45160f42ce0656e27a2b125a558c05a5/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ExecutingSqlQueries.Net46.cs which covers all these cases. The code paths are the same for Mono.SqlLite. I don't see the value to repeat all the cases again.

2023-06-20 09:45 UTC, merged