Remove redundant DiagnosticAnalyzer attributes
SonarSource/sonar-dotnet pull request #7539
Opened 2023-07-05 11:54 UTC by costin-zaharia-sonarsource

2023-07-05 13:12 UTC, csaba-sagi-sonarsource requested changes
Do you mind adding a couple of UTs to https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs that make sure that classes derived from SymbolicRuleCheck do not have this attribute and one that checks that the classes that have them derive from the correct base class?

2023-07-05 13:36 UTC, costin-zaharia-sonarsource commented
I don't mind at all :) I even think we should not restrict only to `SymbolicRuleCheck derived` classes. We can make the check more general to check that all the classes that have the attribute derive from DiagnosticAnalyzer.

2023-07-05 14:01 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2023-07-05 14:17 UTC, merged

2023-07-07 08:32 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/Common/RuleTest.cs
> +        public void AllClassesWithDiagnosticAnalyzerAttribute_InheritSonarDiagnosticAnalyzer()
Nice