Migrate S3329 Scaffold the rule for the new SE
SonarSource/sonar-dotnet pull request #7563
Opened 2023-07-10 11:40 UTC by mary-georgiou-sonarsource

Part of #7559

2023-07-10 13:22 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp8.cs
> +﻿using System;
Here I practically added any test with a `using` statement.

2023-07-11 09:42 UTC, Tim-Pohlmann requested changes
Some minor changes required.

2023-07-11 09:42 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
> +        public void InitializationVectorShouldBeRandom_Sonar_DoesNotRaiseIssuesForTestProject() =>
```suggestion
        public void InitializationVectorShouldBeRandom_DoesNotRaiseIssuesForTestProject_Sonar() =>
```

2023-07-11 09:42 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp8.cs
> +{
Kill the noise! :D
```suggestion
```

2023-07-11 09:42 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
> +{
Kill the noise!
```suggestion
```

2023-07-11 09:42 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
> +//                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
//                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2023-07-11 12:15 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp8.cs
> +{
🪓

2023-07-11 12:55 UTC, Tim-Pohlmann approved these changes
LGTM.
@pavel-mikula-sonarsource please merge this commit. The quality gate fails because this is a scaffolding PR.

2023-07-12 13:15 UTC, merged