Add reproducer
SonarSource/sonar-dotnet pull request #7634
Opened 2023-07-21 08:04 UTC by martin-strecker-sonarsource

Fixes #

2023-07-21 11:35 UTC, pavel-mikula-sonarsource commented
I'd name the PR `S2930: Add FN repro for #7635` to have consistent commit history.

2023-07-24 08:09 UTC, antonioaversa requested changes
Some more testing to capture the generic interface

2023-07-24 11:00 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.ILogger.cs
> +using System;
Now it is ;:)

2023-07-25 08:40 UTC, antonioaversa approved these changes
LGTM

2023-07-25 08:41 UTC, antonioaversa commented
@martin-strecker-sonarsource : Master is currently frozen. I let you merge this one, once the release is done and the branch is unfrozen.

2023-07-25 16:43 UTC, merged