Fix S1186 FP: Empty method comes from interface
SonarSource/sonar-dotnet pull request #7658
Opened 2023-07-24 15:30 UTC by cristian-ambrosini-sonarsource

Fixes #7629

2023-07-25 09:44 UTC, martin-strecker-sonarsource requested changes
Some small changes and a question about the location of the new extension method.

2023-07-25 09:44 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
> +        public static ImmutableArray<ISymbol> ExplicitOrImplicitInterfaceImplementations(this ISymbol symbol)
I have created this trello card in How we work about the placement of the helpers:
https://trello.com/c/nw3yLmEY
See also my comment about coverage there.

2023-07-25 09:44 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.Common/Extensions/ISymbolExtensions.cs
> +        public static ImmutableArray<ISymbol> ExplicitOrImplicitInterfaceImplementations(this ISymbol symbol)
Consider also adding the complementing methods that are available in Roslyn, like `ImplicitInterfaceImplementations` and `ExplicitInterfaceImplementations`. We should only do this after the trello card is resolved.

2023-07-25 09:44 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/EmptyMethod.cs
> +                && (symbol is { IsOverride: true, OverriddenMethod.IsAbstract: true } || symbol.ExplicitOrImplicitInterfaceImplementations().Any()))
```suggestion
                && (symbol is { IsOverride: true, OverriddenMethod.IsAbstract: true } || !symbol.ExplicitOrImplicitInterfaceImplementations().IsEmpty))
```

2023-07-25 12:52 UTC, martin-strecker-sonarsource reviewed
LGTM
The changes in ITs seem reasonable.

2023-07-26 09:52 UTC, merged

2023-08-03 11:27 UTC, cristian-ambrosini-sonarsource commented
Peach validation:
- 2603 lost FPs. I checked randomly more than 50 and they were all methods coming from an interface.