Migrate S2583/S2589: Implement ShouldExecute
SonarSource/sonar-dotnet pull request #7718
Opened 2023-08-03 07:58 UTC by mary-georgiou-sonarsource

Fixes #7646

2023-08-03 08:30 UTC, mary-georgiou-sonarsource commented
@Tim-Pohlmann I guess you can take a first look - and then we see again after the PR for secondary locations is merged.

2023-08-03 14:39 UTC, Tim-Pohlmann requested changes
Please adjust our tests so that we have at least one method for each listed SyntaxKind that does not include any of the others.

2023-08-03 14:39 UTC, Tim-Pohlmann commented on analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> +                    SyntaxKind.SwitchStatement);
Add: ConditionalAccessExpression `?.`, ConditionalExpression `? :`
Remove: LogicalNotExpression `!` (does not call ConditionEvaluated)
Change order to alphabetical
```suggestion
                ContainsCondition = node.IsAnyKind(
                    SyntaxKind.CoalesceExpression,
                    SyntaxKind.ConditionalAccessExpression,
                    SyntaxKind.ConditionalExpression,
                    SyntaxKind.DoStatement,
                    SyntaxKind.ForStatement,
                    SyntaxKind.IfStatement,
                    SyntaxKind.LogicalAndExpression,
                    SyntaxKind.LogicalOrExpression,
                    SyntaxKindEx.SwitchExpression,
                    SyntaxKind.SwitchStatement,
                    SyntaxKind.WhileStatement);
```

2023-08-04 14:50 UTC, Tim-Pohlmann requested changes
Please adjust our tests so that we have at least one method for each listed SyntaxKind that does not include any of the others.

2023-08-07 07:19 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
> +    int SwitchExpression()
Tests are in C# 8 file because of the `SwitchExpression` test.

2023-08-07 08:12 UTC, Tim-Pohlmann approved these changes
LGTM. I would have just adjusted the existing test cases. But this works as well.
Please rebase and make sure the pipeline is green (except for ITs).

2023-08-07 08:25 UTC, mary-georgiou-sonarsource commented
@Tim-Pohlmann I'll re-base and re-adjust if needed after the secondary locations are merged.
If it makes sense I'll re-ask for review.

2023-08-08 08:18 UTC, merged