New rule S2589/S2583 for VB.NET
SonarSource/sonar-dotnet pull request #7727
Opened 2023-08-04 13:29 UTC by mary-georgiou-sonarsource

Fixes #7647 #7648

2023-08-10 09:46 UTC, mary-georgiou-sonarsource commented
@Tim-Pohlmann Take a first look - implementation + UTs is done.
What is not done is the rspecs fro these two rules. 
I'll update you later with links the PRs.

2023-08-10 15:13 UTC, Tim-Pohlmann requested changes
Some polishing required

2023-08-10 15:13 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +                    s1.ToString()  ' Secondary
formatting

2023-08-10 15:13 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +
formatting

2023-08-10 15:18 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.VB14.vb
> +                End Function
IMO it's overengineered code to be used for the cases below.
I will simplify it.

2023-08-10 15:20 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.VB14.vb
> +                End Function
The old engine might have looked inside other methods.

2023-08-10 15:48 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.VB14.vb
> +        End Sub
🤦

2023-08-10 15:54 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +        Public Sub Method9_For(ByVal cond As Boolean)
I removed also previous one - for loops don't make sense here base on the docs.

2023-08-10 15:55 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            End Select
Simplicity - I just wanted to make sure we raise in switch for VB.NET.

2023-08-10 16:10 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +        End Sub
No idea - could you point me to the C# equivalent?

2023-08-10 16:10 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            If Not Equals(String.IsInterned(s), Nothing) Then ' FN FIX
It's not!

2023-08-10 16:14 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            End If
Copied and forgotten from C#.
I turned those to FN due to relation support missing.

2023-08-10 16:15 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            While If(input, False) ' Noncompliant
Same in C# - maybe we should check what happens with nullable objects?

2023-08-11 06:50 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.VB14.vb
> +                Console.WriteLine("a")                  ' Secondary
The length of the Secondary location is off. But this will be fixed by #7725

2023-08-11 06:50 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.VB14.vb
> +            '                 ^^^^^^^        Secondary@-1
The length of the Secondary location is off. But this will be fixed by #7725

2023-08-11 06:50 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
> +            if (a)                  // FN
This is only an FN because of the compound assignments above. Needs to be separated.

2023-08-11 06:50 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +        End Sub
https://github.com/SonarSource/sonar-dotnet/blob/b6cb8aff9ec3ef81a0654eab93034eae64bcf23d/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs#L678-L701

2023-08-11 06:53 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +                    ' Error@-1 [BC30020]
Align it with the other comment.

2023-08-11 06:54 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            ' and to avoid False Positives we do not report in catch or finally
Change is not applied to C#

2023-08-11 06:56 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            If Equals(Nothing, NameOf(Method1)) Then ' FN FIX
Added a task to do this after this PR - I will reply with issue number in this message.

2023-08-11 06:56 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            If Equals(Nothing, NameOf(Method1)) Then ' FN FIX
Did you create the issue?

2023-08-11 06:57 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            While If(input, False) ' Noncompliant
I'll take a quick look later.

2023-08-11 06:59 UTC, Tim-Pohlmann approved these changes
LGTM, only minor nitpicks left.

2023-08-11 07:04 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +        End Sub
Re-added to VB

2023-08-11 07:45 UTC, merged

2023-08-11 08:18 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
> +            If Equals(Nothing, NameOf(Method1)) Then ' FN FIX
No need to open an issue - it's noncompliant for VB14+