Update the plugin api
SonarSource/sonar-dotnet pull request #7777
Opened 2023-08-10 15:30 UTC by costin-zaharia-sonarsource

In order to be able to update the RSPEC for clean code taxonomy.

2023-08-14 08:20 UTC, costin-zaharia-sonarsource commented on sonar-csharp-plugin/pom.xml
> +    <sonarLTS.version>9.9</sonarLTS.version>
Updated to be in sync with the java plugin: https://github.com/SonarSource/sonar-java/pull/4416/files#diff-a2a59812e774224a494679a03de77f5fe24ceb84295e379d6b9583ef97a1ee15R124

2023-08-14 14:57 UTC, antonioaversa requested changes
Mostly remarks on the use of variables, questions on the dependency management across pom files and improvements on logging.

2023-08-14 14:57 UTC, antonioaversa commented on sonar-vbnet-plugin/pom.xml
> +    <sonarLTS.version>9.9</sonarLTS.version>
Same comment as for the C# version.

2023-08-14 16:23 UTC, costin-zaharia-sonarsource commented on sonar-csharp-plugin/pom.xml
> +    <sonarLTS.version>9.9</sonarLTS.version>
The variable is not defined on the java plugin, the value is used directly to set the value for <sonarQubeMinVersion> parameter for the `sonar-packaging-maven-plugin` which I think we do use
https://github.com/SonarSource/sonar-dotnet/blob/master/sonar-vbnet-plugin/pom.xml#L187-L195.

2023-08-14 16:24 UTC, costin-zaharia-sonarsource commented on pom.xml
>      <!-- We are ignoring java doc warnings - this is because we are using JDK 11. Ideally we should not do that. -->
I'm not sure about this but it's not related to this PR. Could you please create a task to check and remove if possible?

2023-08-14 16:26 UTC, costin-zaharia-sonarsource commented on pom.xml
> +        <groupId>org.sonarsource.analyzer-commons</groupId>
I think it makes sense. I moved some of them but I wouldn't move all of them. I'll try to update the ones that I've touched.

2023-08-14 16:32 UTC, costin-zaharia-sonarsource commented on sonar-dotnet-shared-library/pom.xml
>        <version>${findbugs.version}</version>
I've missed this one. Thanks!

2023-08-15 07:15 UTC, costin-zaharia-sonarsource commented on pom.xml
> +        <groupId>org.sonarsource.analyzer-commons</groupId>
We need to keep the property for analyzer commons since it's used also for `sonar-xml-parsing`

2023-08-15 08:27 UTC, antonioaversa commented on pom.xml
> +        <groupId>org.sonarsource.analyzer-commons</groupId>
Oh, I missed that, makes sense!

2023-08-15 08:38 UTC, antonioaversa approved these changes
LGTM, thanks for all the explanations!
I left a minor comment about inlining a short ternary operator.
It is optional, and in case can come in a later PR.

2023-08-15 08:38 UTC, antonioaversa commented on sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/CallableUtils.java
> +          return result == null
I would write this ternary inline, since it's short and simple to understand.

2023-08-15 10:01 UTC, merged