Delete S4787 (Deprecated)
SonarSource/sonar-dotnet pull request #7939
Opened 2023-09-01 13:05 UTC by mary-georgiou-sonarsource

2023-09-04 15:03 UTC, Tim-Pohlmann requested changes
The changes to the ruleset file seem weird. The rest looks fine.

2023-09-05 06:39 UTC, mary-georgiou-sonarsource commented on analyzers/its/AllSonarAnalyzerRules.ruleset
> +    <Rule Id="S2255" Action="Warning" />
No - so I deleted it in the previous rule deletion S2255 but I should not have.
This is just a ruleset of continuous ids. I should not have touched it.

2023-09-05 06:39 UTC, mary-georgiou-sonarsource commented on analyzers/its/SingleRule.ruleset.template
> +    <Rule Id="S4788" Action="None" />
I deleted and re-added it. 
Then rebased and re-added twice probably.
Good catch thanks!

2023-09-06 06:36 UTC, Tim-Pohlmann approved these changes
LGTM

2023-09-06 06:37 UTC, merged