Fix S4158 FP: The analyzer incorrectly concludes the HashSet is guaranteed to be empty
SonarSource/sonar-dotnet pull request #8066
Opened 2023-09-25 14:21 UTC by Tim-Pohlmann

Fixes #8041
Fixes #7582

We recently improved how the SE engine handles loops (#7795). We missed to include foreach loops in the process.

2023-09-27 07:24 UTC, mary-georgiou-sonarsource requested changes
Please add a reprocude also for the issue itself
https://github.com/SonarSource/sonar-dotnet/issues/8041

2023-10-04 09:22 UTC, Tim-Pohlmann commented
@mary-georgiou-sonarsource is this necessary? There are multiple similar UTs in the code base already, which are getting fixed by this PR.

2023-10-09 10:50 UTC, MaStr11 commented on analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/VisualBasicSyntaxClassifier.cs
> +            ForEachStatementSyntax foreachStatement => foreachStatement.Expression,
Misses https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntax.foreachvariablestatementsyntax?view=roslyn-dotnet-4.6.0

e.g `foreach(var (i, j) in new (int, int)[0])`

Should be `CommonForEachStatementSyntax` instead.

2023-10-16 06:50 UTC, mary-georgiou-sonarsource approved these changes
LGTM

2023-10-16 06:50 UTC, merged