S2589: Add repro fro 8045
SonarSource/sonar-dotnet pull request #8088
Opened 2023-09-27 08:25 UTC by mary-georgiou-sonarsource

Related to #8045

2023-10-04 07:13 UTC, Tim-Pohlmann commented
I would move this test to [`CollectionConstraintTests`](https://github.com/SonarSource/sonar-dotnet/blob/176773cc9d6846edb60834a29187575d2cc53344/analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/CollectionConstraintTests.cs).

2023-10-10 09:17 UTC, Tim-Pohlmann requested changes
As mentioned above, I would merge this with the other test file.

2023-10-10 09:17 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
> +        .Verify();
```suggestion
    public void ConditionEvaluatesToConstant_Roslyn_CS_WithS4158() =>
        roslynCS.AddPaths("ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs")
        .WithOnlyDiagnostics(ChecksCS.ConditionEvaluatesToConstant.S2583, ChecksCS.ConditionEvaluatesToConstant.S2589, ChecksCS.EmptyCollectionsShouldNotBeEnumerated.S4158)
        .Verify();
```

2023-10-10 09:17 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs
> +        private int Length { get; }
```suggestion
    {
        private int Length { get; }
```

2023-10-10 09:17 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs
> +namespace Tests.Diagnostics
Change it to file-scoped.

2023-10-10 09:17 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs
> +        private int Length { get; }
```suggestion
        int Length { get; }
```

2023-10-10 09:17 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs
> +            bool result = foo.Contains("foo");
Add a comment to explain that this is needed to trigger the rule via `ShouldExecute`.

2023-10-16 11:47 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs
> +        private int Length { get; }
obsolete

2023-10-16 11:47 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs
> +namespace Tests.Diagnostics
obsolete

2023-10-16 11:47 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.EmptyCollectionsShouldNotBeEnumerated.cs
> +        private int Length { get; }
obsolete

2023-10-16 12:50 UTC, merged