FN S2190: No issues raised if recursion is inside indexer, conversion operator or event declaration
SonarSource/sonar-dotnet pull request #8464
Opened 2023-12-14 00:10 UTC by sagi1623

Fixes #6642 
Fixes #6643 
Fixes #6644

2023-12-18 12:21 UTC, cristian-ambrosini-sonarsource commented
/azp run

2023-12-22 11:36 UTC, sagi1623 commented
I fixed the code smells and opened an [issue](https://github.com/SonarSource/sonar-dotnet/issues/8502) for the rest of the FPs that remain in the file. Regarding the coverage I could not come up with any valid or invalid code snippet that would cover the cases, however I would rather leave it there as defensive coding than to create AD0001s if anything changes in Roslyn.

2024-01-15 13:08 UTC, cristian-ambrosini-sonarsource commented
/azp run

2024-01-15 14:08 UTC, cristian-ambrosini-sonarsource requested changes
Left few ideas to bump the coverage

2024-06-03 12:17 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/InfiniteRecursion.SonarCfg.cs
> +            }
We don't support and we don't care about the sonar SE engine. It's deprecated.

2024-06-03 13:03 UTC, mary-georgiou-sonarsource commented
/azp run

2024-06-03 14:08 UTC, mary-georgiou-sonarsource commented
/azp-run

2024-06-03 14:44 UTC, mary-georgiou-sonarsource commented
/azp run

2024-06-03 15:18 UTC, mary-georgiou-sonarsource commented
/azp  run

2024-06-07 08:53 UTC, CristianAmbrosini approved these changes
LGTM! Feel free to rebase and merge

2024-06-07 08:53 UTC, CristianAmbrosini commented
@sagi1623 Freedom! Finally 😄

2024-06-07 13:30 UTC, mary-georgiou-sonarsource commented
/azp run

2024-06-07 14:00 UTC, mary-georgiou-sonarsource commented
/azp run

2024-06-07 14:13 UTC, merged