Add SE test cases for C# 12 collection expressions
SonarSource/sonar-dotnet pull request #8540
Opened 2024-01-15 22:14 UTC by zsolt-kolbay-sonarsource

Reproduces #8539

2024-01-16 12:21 UTC, gregory-paidis-sonarsource approved these changes
LGTM

2024-01-16 16:45 UTC, pavel-mikula-sonarsource requested changes
This PR will be affected by the UnitTest->Test rename. 

At the same time, I noticed that both files were wrong.

2024-01-16 16:45 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/EmptyCollectionsShouldNotBeEnumeratedTest.cs
> +public class EmptyCollectionsShouldNotBeEnumeratedTest
Adding new file for existing rule is a big red flag. The new UT should be in the existing file.

2024-01-16 16:45 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/EmptyCollectionsShouldNotBeEnumerated.cs
> +﻿using System;
This file has wrong name and lives in a wrong directory.

2024-01-16 16:56 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/EmptyCollectionsShouldNotBeEnumeratedTest.cs
> +public class EmptyCollectionsShouldNotBeEnumeratedTest
As Greg pointed out, it's .NET 8 that I missed. In that case only the namespace is wrong and should be the same as in other files in the same directory.

..and will need to be updated to `.Test.` after #8544 is done

2024-01-16 16:56 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/EmptyCollectionsShouldNotBeEnumerated.cs
> +﻿using System;
...ah, it's .NET8 so i'ts fine 🤦

2024-01-17 10:56 UTC, pavel-mikula-sonarsource commented
The directory rename PR was merged, so you can move the new files now

2024-01-18 10:09 UTC, zsolt-kolbay-sonarsource commented on analyzers/tests/SonarAnalyzer.Net8.Test/Rules/EmptyCollectionsShouldNotBeEnumeratedTest.cs
> +        roslynCS.AddPaths("EmptyCollectionsShouldNotBeEnumerated.cs").WithOptions(ParseOptionsHelper.FromCSharp12).Verify();
Right, I forgot it doesn't need runtime support. I moved it out of the .NET 8 project.

2024-01-18 10:12 UTC, gregory-paidis-sonarsource commented on analyzers/tests/SonarAnalyzer.Net8.Test/Rules/EmptyCollectionsShouldNotBeEnumeratedTest.cs
> +        roslynCS.AddPaths("EmptyCollectionsShouldNotBeEnumerated.cs").WithOptions(ParseOptionsHelper.FromCSharp12).Verify();
Ah I missed that too.
The normal UT framework sets `LanguageVersion.Latest`, which is enough to use the new collection expression 🤦

2024-01-22 16:04 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2024-01-22 16:05 UTC, merged