Move Net5 project from .NET ITs to Java ITs
SonarSource/sonar-dotnet pull request #8920
Opened 2024-03-13 16:25 UTC by gregory-paidis-sonarsource

Part of this [background task](https://trello.com/c/WMQOKenL/1255-move-sdk-based-net-its-to-java-its)

2024-03-13 16:33 UTC, gregory-paidis-sonarsource commented on its/src/test/java/com/sonar/it/csharp/SdkTest.java
> +    project_should_have_metrics_and_issues("Net5");
Extracted this since I will re-use it in follow-up PR for the rest of the SDK projects.

2024-03-14 08:02 UTC, pavel-mikula-sonarsource requested changes
Minor polishing

2024-03-14 08:02 UTC, pavel-mikula-sonarsource commented on its/src/test/java/com/sonar/it/csharp/SdkTest.java
> +    assertThat(getMeasureAsInt(project, "lines")).isEqualTo(5);
Just heads up: This might become parametrized in the future. Hardcoding is fine for now.

2024-03-14 08:59 UTC, gregory-paidis-sonarsource commented on its/src/test/java/com/sonar/it/csharp/SdkTest.java
> +}
What are you referring to? 🤔

2024-03-14 09:12 UTC, pavel-mikula-sonarsource commented on its/src/test/java/com/sonar/it/csharp/SdkTest.java
> +}
.NET (n+1) might raise additional issue, that might require additional line to avoid. So no problem for now

2024-03-18 12:38 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2024-03-20 12:38 UTC, merged