Cleanup and removal of the old implementation
SonarSource/sonar-dotnet pull request #9190
Opened 2024-04-23 14:17 UTC by CristianAmbrosini

Fixes #9010

2024-04-25 14:38 UTC, Tim-Pohlmann requested changes
The main code changes look good. I have some comments about the tests.

2024-04-26 07:08 UTC, CristianAmbrosini commented on analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextTest.Register.cs
> +            .WithOptions(ParseOptionsHelper.FromCSharp9)
Not needed indeed

2024-04-26 07:41 UTC, CristianAmbrosini commented on analyzers/tests/SonarAnalyzer.Test/Rules/UnnecessaryUsingsTest.cs
> +            builder.AddSnippet(@"@using System.Text.Json;", fileName).VerifyNoIssueReported(); // ToDo TAKE A LOOK
Yeah, we added this comment for some reason, but I don't remember why. @sebastien-marichal, do you have any idea?

2024-04-26 08:00 UTC, sebastien-marichal commented on analyzers/tests/SonarAnalyzer.Test/Rules/UnnecessaryUsingsTest.cs
> +            builder.AddSnippet(@"@using System.Text.Json;", fileName).VerifyNoIssueReported(); // ToDo TAKE A LOOK
My guess would be that we saw the test is green even though we don't provide the `System.Text.Json` reference. Which seems to be needed in the next test.

It probably should have a compilation error or we don't need to provide the reference in the next test.

2024-04-26 08:57 UTC, CristianAmbrosini commented on analyzers/tests/SonarAnalyzer.TestFramework/Dependencies/Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.deps.json
let's keep it there, it's a temporary solution anyway, the entire folder will be removed in the follow up PR

2024-04-26 08:57 UTC, CristianAmbrosini commented on analyzers/tests/SonarAnalyzer.TestFramework/Dependencies/RazorSourceGenerator.razorencconfig
Same as above

2024-04-26 13:00 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.Test/Rules/UnnecessaryUsingsTest.cs
> +            builder.AddSnippet(@"@using System.Text.Json;", fileName).VerifyNoIssueReported(); // ToDo TAKE A LOOK
The difference lies in `Verify` vs. `VerifyNoIssueReported`. I'm not sure why exactly, but the test is fine as is.

2024-04-26 13:02 UTC, Tim-Pohlmann approved these changes
LGTM!

2024-04-26 13:03 UTC, merged