Refactor: Extract common method to check if any ancestor belongs to SyntaxKind
SonarSource/sonar-dotnet pull request #9202
Opened 2024-04-24 15:31 UTC by mary-georgiou-sonarsource

2024-04-25 11:27 UTC, gregory-paidis-sonarsource approved these changes
LGTM

2024-04-29 13:36 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Common/Walkers/MutedSyntaxWalker.cs
> -        private static bool HasAncestor(SyntaxNode node, SyntaxKind kind) =>
it has 0 references in the project.

2024-04-29 13:37 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
> -        IsOn(expression, SyntaxKind.BaseExpression);
this has 0 references in the project.

2024-05-01 16:01 UTC, pavel-mikula-sonarsource requested changes
Some cleanup

2024-05-02 11:06 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2024-05-02 11:06 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
> +                && node.HasAncestor(AwaitExpression,
[T0028](https://github.com/SonarSource/sonar-dotnet/issues/9161)
```suggestion
                && node.HasAncestor(
                    AwaitExpression,
```

2024-05-02 11:06 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
> +                && node.HasAncestor(AwaitExpression,
You can fix this in your next PR, I'll merge this one now as I need to nuke the whole helper file

2024-05-02 11:07 UTC, merged