Improve S1694: Remove part about protected constructor
SonarSource/sonar-dotnet pull request #9387
Opened 2024-06-04 09:18 UTC by pavel-mikula-sonarsource

Fixes #8795

2024-06-05 09:45 UTC, CristianAmbrosini requested changes
A few lines can be removed without failing the UTs

2024-06-05 09:45 UTC, CristianAmbrosini commented on analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeAbstract.cs
> +public abstract partial class A
This is a really interesting test in the Noncompliant version:
```cs
public abstract partial class A // Noncompliant
{
    public abstract void X();
}
public abstract partial class A // Noncompliant
{
    public abstract void Y();
}
```

2024-06-05 09:45 UTC, CristianAmbrosini commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeAbstract.cs
> +public sealed class ClassShouldNotBeAbstract : SonarDiagnosticAnalyzer<SyntaxKind>
The name of this class is not the best IMO, what about `AbstractClassShouldContainConcreteMethods`, or a shorter version of it

2024-06-06 08:41 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeAbstract.cs
> +                    && !HasInheritedAbstractMembers(symbol)
symbol.IsAbstract is a performance shortcut

2024-06-06 08:47 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeAbstract.cs
> +                    && !HasInheritedAbstractMembers(symbol)
`HasInheritedAbstractMembers` is a good catch! It's already excluded by `symbol.BaseType.Is(KnownType.System_Object)`  check

2024-06-06 10:14 UTC, CristianAmbrosini approved these changes
LGTM!

2024-06-06 10:14 UTC, merged