Fix S1144 FP: types used through reflection
SonarSource/sonar-dotnet pull request #9406
Opened 2024-06-05 12:39 UTC by zsolt-kolbay-sonarsource

Fixes #9379

2024-06-05 15:03 UTC, martin-strecker-sonarsource requested changes

2024-06-06 08:41 UTC, CristianAmbrosini commented on analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp9.cs
> +            private void Method([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] NestedType arg) { }
There's already a test for private properties

2024-06-06 09:29 UTC, CristianAmbrosini commented on analyzers/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs
> +            if (symbolsUsedWithReflection.Contains(currentSymbol))
This is compliant with the current implentation, I'm not sure we need the OriginalDefinition

2024-06-06 12:42 UTC, martin-strecker-sonarsource requested changes
It generally looks fine. It misses some UTs that might be worth adding. Feel free not to add them if you think it's not worth it.

2024-06-06 12:42 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
> +            if (semanticModel.GetSymbolInfo(node).Symbol is { } symbol)
NIT: as in the other PR: `semanticModel.GetSymbolInfo(node).Symbol is IMethodSymbol { MethodKind:Constructor, Parent: ITypeSymbol attribute } `

2024-06-06 12:42 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
> +            static ImmutableArray<ITypeParameterSymbol> GetMethodTypeParameters(ISymbol symbol) =>
Might be inlined or needs to be named `GetTypeParameters`

2024-06-06 12:42 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp9.cs
> +            (T)Activator.CreateInstance(typeof(T), 42);
According [to the docs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-8.0#remarks), the attribute also works for `string` and `Type` parameters:
```cs
public static object CreateInstance([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type) => // ..

CreateInstance(typeof(SomePrivateClass));
```

You may want to add an FP UT.

2024-06-06 12:42 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp9.cs
> +            private bool a = true; // Noncompliant FP: type argument is inferred and ArgumentList is not present on syntax level
Can you point to the place where the FP originates from. It is hard to see that line 183 is related to this code.

2024-06-06 12:42 UTC, martin-strecker-sonarsource commented on analyzers/tests/SonarAnalyzer.Test/TestCases/UnusedPrivateMember.CSharp9.cs
> +            private int PrivateMethodWithReturn() { return 0; } // Noncompliant
The FP here is that the return type is not detected. Replace `int` with some private class a trimmer might remove.

2024-06-10 09:33 UTC, zsolt-kolbay-sonarsource commented
I removed the check through type parameters, because it nearly doubled the analysis time.
We'll need to accept it as FP.

2024-06-10 12:46 UTC, martin-strecker-sonarsource commented
> I removed the check through type parameters, because it nearly doubled the analysis time.
We'll need to accept it as FP.

How did you measure? If the rule was very, very fast, duplication is not a problem. Can you post some more info about the perf validation?

2024-06-10 16:02 UTC, martin-strecker-sonarsource requested changes

2024-06-11 15:27 UTC, zsolt-kolbay-sonarsource commented
> > I removed the check through type parameters, because it nearly doubled the analysis time.
> > We'll need to accept it as FP.
> 
> How did you measure? If the rule was very, very fast, duplication is not a problem. Can you post some more info about the perf validation?

I used the [AnalyzerRunner](https://github.com/dotnet/roslyn/tree/main/src/Tools/AnalyzerRunner) from the Roslyn repo to compare the performance with and without the check for type parameters. I ran it on _AutoMapper_, _Akka.Net_, and an earlier version of the _Roslyn_ repo. They all showed a degradation in performance ranging between 40% and 90%. `UnusedPrivateMember` is one of the slowest rules we have (excluding SE rules), so I don't think such a change is acceptable.

```
WITHOUT the check for type arguments (AutoMapper):

Statistics for UnusedPrivateMember:
Concurrent:                     False
Execution time (ms):            3644.8062
Code Block Actions:             0
Code Block Start Actions:       0
Code Block End Actions:         0
Compilation Actions:            0
Compilation Start Actions:      6
Compilation End Actions:        6
Operation Actions:              0
Operation Block Actions:        0
Operation Block Start Actions:  0
Operation Block End Actions:    0
Semantic Model Actions:         0
Symbol Actions:                 6
Symbol Start Actions:           0
Symbol End Actions:             0
Syntax Node Actions:            0
Syntax Tree Actions:            0
Additional File Actions:        0
Suppression Actions:            0
Execution times (ms):
UnusedPrivateMember:    3645
  S1144: 1364 instances
  S4487: 9 instances

--------------------------------------------------------
--------------------------------------------------------

INCLUDING the check for type arguments (AutoMapper):

Statistics for UnusedPrivateMember:
Concurrent:                     False
Execution time (ms):            5731.9556
Code Block Actions:             0
Code Block Start Actions:       0
Code Block End Actions:         0
Compilation Actions:            0
Compilation Start Actions:      6
Compilation End Actions:        6
Operation Actions:              0
Operation Block Actions:        0
Operation Block Start Actions:  0
Operation Block End Actions:    0
Semantic Model Actions:         0
Symbol Actions:                 6
Symbol Start Actions:           0
Symbol End Actions:             0
Syntax Node Actions:            0
Syntax Tree Actions:            0
Additional File Actions:        0
Suppression Actions:            0
Execution times (ms):
UnusedPrivateMember:    5732
  S1144: 1364 instances
  S4487: 9 instances
```

2024-06-11 16:30 UTC, martin-strecker-sonarsource requested changes
Can you also update the RSpec? It needs the `DynamicallyAccessedMembersAttribute` in the exception section. Consider only checking only the name of the attribute instead of namespace/name. This would allow users to create this attribute in unsupported platforms (which is every platform except Net5 upwards). The name is long enough to not be confused with anything else. If you go that route, tests are needed.

2024-06-11 16:30 UTC, martin-strecker-sonarsource commented on analyzers/packaging/output/Akka.API.Tests/net471/SonarProjectConfig.xml
> +<SonarProjectConfig xmlns="http://www.sonarsource.com/msbuild/analyzer/2021/1">
Upps. These files do not belong here.

2024-06-13 11:22 UTC, martin-strecker-sonarsource approved these changes
LGTM. I think a comment is helpful in this case.

2024-06-13 11:22 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
> +        if (node.GetName() is "DynamicallyAccessedMembersAttribute" or "DynamicallyAccessedMembers"
```suggestion
        // Some members that seem unused might be dynamically accessed through reflection.
        // The DynamicallyAccessedMembersAttribute was introduced to inform tools about such uses.
        // The attribute is not available on NetFramework and we want to enable this mechanism for these users. 
        // Therefore, we only check the name, but not the namespace and let the users define their own custom version.
        // https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute
        if (node.GetName() is "DynamicallyAccessedMembersAttribute" or "DynamicallyAccessedMembers"
```

2024-06-13 11:22 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSymbolUsageCollector.cs
> +        if (node.GetName() is "DynamicallyAccessedMembersAttribute" or "DynamicallyAccessedMembers"
Consider making "DynamicallyAccessedMembers" a const:
```suggestion
        const string DynamicallyAccessedMembers = "DynamicallyAccessedMembers";
        if (node.GetName() is DynamicallyAccessedMembers or $"{DynamicallyAccessedMembers}Attribute"
```

2024-06-13 12:43 UTC, merged