Shimlayer: Light up TypeArgumentNullableAnnotations
SonarSource/sonar-dotnet pull request #9413
Opened 2024-06-06 17:08 UTC by martin-strecker-sonarsource

Precondition for #8413

2024-06-10 16:56 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/ShimLayer/INamedTypeSymbolExtensions.cs
> +            // The generated code
Maybe it is far easier to use [`ImmutableArray.CreateRange<TSource,TResult>(ImmutableArray<TSource>, Func<TSource,TResult>)`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray.createrange?view=net-8.0#system-collections-immutable-immutablearray-createrange-2(system-collections-immutable-immutablearray((-0))-system-func((-0-1)))) instead?

2024-06-10 19:06 UTC, martin-strecker-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/ShimLayer/INamedTypeSymbolExtensions.cs
> +            // The generated code
Done in e1a5ef63f534c8f270554868e731d681debb6224

2024-06-14 14:16 UTC, pavel-mikula-sonarsource requested changes
One question about the code placement

2024-06-14 14:16 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/ShimLayer/INamedTypeSymbolExtensions.cs
> +        public static ImmutableArray<NullableAnnotation> TypeArgumentNullableAnnotations(this INamedTypeSymbol symbol) => TypeArgumentNullableAnnotationsAccessor(symbol);
Is this present in the StyleCop repo too, or is it only our addition? 
Shouldn't it follow the new file structure where we said that we'll put our changes on a side?

2024-06-14 14:16 UTC, pavel-mikula-sonarsource commented on analyzers/tests/SonarAnalyzer.Test/Wrappers/INamedTypeSymbolExtensionsTests.cs
> +        typeArgumentNullabilityShim.Should().BeEquivalentTo([expected]).And.BeEquivalentTo(typeArgumentNullability.Select(x => (NullableAnnotation)x));
This is heavy and repetitive. Let's extract it.
```suggestion
        ValidateTypeArgumentNullableAnnotations(code, expected);
```

2024-06-19 16:43 UTC, pavel-mikula-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/ShimLayer/INamedTypeSymbolExtensions.cs
> +        public static ImmutableArray<NullableAnnotation> TypeArgumentNullableAnnotations(this INamedTypeSymbol symbol) => TypeArgumentNullableAnnotationsAccessor(symbol);
We defined how to do our extensions of ShimLayer on this card:
https://trello.com/c/fxLbcSr2/77-shimlayer-how-do-we-keep-track-of-our-own-changes?filter=shim
and that resulted in this document
https://docs.google.com/document/d/1hkE_jH8vjsT7phgZ16-RF-uNYmcNDGN8ITBr4pBTGMc/edit#heading=h.iov8d4fboa5j

We went for `Sonar` directory there.

2024-06-19 16:44 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2024-06-20 13:35 UTC, merged