Fix S1854 FP: Throw should visit finally
SonarSource/sonar-dotnet pull request #9530
Opened 2024-07-16 15:46 UTC by sebastien-marichal

Fixes #9466

2024-07-18 15:23 UTC, mary-georgiou-sonarsource requested changes
Some refactoring

2024-07-18 15:23 UTC, mary-georgiou-sonarsource commented on analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
> +    public void TryCatchFinally_RethrowWithFinally()
```suggestion
    public void TryCatchFinally_Rethrow_ValueLivesOut()
```

2024-07-18 15:23 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
> +    private void BuildBranchesRethrowFinally(BasicBlock block)
I think we can merge this method with the method I added for the similar case (catch -> outercatch connection if there's a rethrow) like so:

```csharp
     private void BuildBranchesRethrow(BasicBlock block)
    {
        var reachableHandlerRegions = block.EnclosingRegion(ControlFlowRegionKind.TryAndCatch).NestedRegion(ControlFlowRegionKind.Try).ReachableHandlers();
        var reachableCatchAndFinallyBlocks = reachableHandlerRegions.Where(x => x.FirstBlockOrdinal > block.Ordinal).SelectMany(x => x.Blocks(Cfg));
        foreach (var catchBlock in reachableCatchAndFinallyBlocks.Where(x => x.EnclosingRegion.Kind is ControlFlowRegionKind.Catch))
        {
            AddBranch(block, catchBlock);
        }
        if (reachableCatchAndFinallyBlocks.FirstOrDefault() is { } branch)
        {
            AddBranch(block, branch);
        }
    }   
```

WDYT?

2024-07-19 07:01 UTC, mary-georgiou-sonarsource requested changes
As discussed I'm not sure why you get the first or default catch or throw.
Please take a look.

2024-07-19 09:56 UTC, mary-georgiou-sonarsource commented on analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
> +        if (reachableCatchAndFinallyBlocks.Any() && reachableCatchAndFinallyBlocks.First() is { EnclosingRegion.Kind: ControlFlowRegionKind.Finally } finallyBlock)
```suggestion
        if (reachableCatchAndFinallyBlocks.FirstOrDefault() is { EnclosingRegion.Kind: ControlFlowRegionKind.Finally } finallyBlock)
```

2024-07-19 14:18 UTC, mary-georgiou-sonarsource approved these changes
LGTM

2024-07-19 14:18 UTC, merged

2024-07-19 14:21 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
> +        const string code = """
`cons string` has no performance benefit over `var`:
https://stackoverflow.com/a/49224799
This creates unnecessary visual noise.