Fix S1172: code fix does not delete unused parameter in function call
SonarSource/sonar-dotnet pull request #9534
Opened 2024-07-18 15:04 UTC by sebastien-marichal

Fixes #8187

It does not support changing usage outside of the current SyntaxTree (e.g.: in case of usage in partial class).

2024-07-18 15:35 UTC, sebastien-marichal commented
Low coverage is due to defensive coding.
I'm not sure I can improve; @tim-pohlmann, if you have any ideas, I'm all ears.

2024-07-19 08:01 UTC, denis-troller commented
Can we make sure we find a way to deal with cases where the argument to remove has a side effect?

```
//...
MyFunction(a, i++);
//... use I later
//...

public void MyFunction(int a, int b)
{
// ... only use a
}
```

2024-07-19 13:52 UTC, Tim-Pohlmann requested changes
Review 1

2024-07-19 13:52 UTC, Tim-Pohlmann commented on analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnusedCodeFix.cs
> +                    .Select(x => GetArgumentFromLocation(x, parameterIndex));
This will not work with out of order named arguments.

2024-07-19 13:52 UTC, Tim-Pohlmann commented on analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnusedCodeFix.cs
> +                    [parameter, ..arguments.Where(x => x is not null)],
Move the `Where` to the assignment of `arguments`.

2024-07-19 13:52 UTC, Tim-Pohlmann commented on analyzers/src/SonarAnalyzer.CSharp/Rules/MethodParameterUnusedCodeFix.cs
> +            }
If you move it to a method you can call it directly from the `RemoveNodes` invocation.

2024-07-19 13:52 UTC, Tim-Pohlmann commented on analyzers/tests/SonarAnalyzer.Test/TestCases/MethodParameterUnused.RoslynCfg.Fixed.cs
> +    }
Add a test with named arguments, which are out of order. Also some tests with optional arguments.

2024-07-19 15:16 UTC, sebastien-marichal commented
As discussed, as arguments can include very complex expressions, I am only removing argument expressions that do no updates whatsoever.

2024-09-23 11:49 UTC, closed without merging